<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Analítica predictiva avanzada - 3&nbsp; Suavizado Exponencial</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./03-etsSSOEenSS.html" rel="next">
<link href="./07-basicsts.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "Sin resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script><script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./02-etsSSOE.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Suavizado Exponencial</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Analítica predictiva avanzada</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prólogo</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introducción</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-basicsts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Conceptos y herramientas básicas</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-etsSSOE.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Suavizado Exponencial</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-etsSSOEenSS.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Suavizado exponencial en Espacio de los Estados</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-etsMSOE.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Suavizado Exponencial con mútiples ruidos</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-extensiones.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Aplicaciones</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-introR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Apéndice A: Introducción a los lenguajes de programación</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-tutorialUComp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Apéndice B: Tutorial de UComp</span></a>
  </div>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Índice</h2>
   
  <ul>
<li>
<a href="#suavizado-exponencial-simple.-componentes-de-nivel-y-error." id="toc-suavizado-exponencial-simple.-componentes-de-nivel-y-error." class="nav-link active" data-scroll-target="#suavizado-exponencial-simple.-componentes-de-nivel-y-error."><span class="header-section-number">3.1</span> Suavizado exponencial simple. Componentes de nivel y error.</a>
  <ul class="collapse">
<li><a href="#media-m%C3%B3vil" id="toc-media-móvil" class="nav-link" data-scroll-target="#media-m%C3%B3vil"><span class="header-section-number">3.1.1</span> Media móvil</a></li>
  <li><a href="#suavizado-exponencial" id="toc-suavizado-exponencial" class="nav-link" data-scroll-target="#suavizado-exponencial"><span class="header-section-number">3.1.2</span> Suavizado exponencial</a></li>
  </ul>
</li>
  <li>
<a href="#evaluaci%C3%B3n-de-las-predicciones" id="toc-evaluación-de-las-predicciones" class="nav-link" data-scroll-target="#evaluaci%C3%B3n-de-las-predicciones"><span class="header-section-number">3.2</span> Evaluación de las predicciones</a>
  <ul class="collapse">
<li><a href="#medidas-de-error-de-predicci%C3%B3n" id="toc-medidas-de-error-de-predicción" class="nav-link" data-scroll-target="#medidas-de-error-de-predicci%C3%B3n"><span class="header-section-number">3.2.1</span> Medidas de error de predicción</a></li>
  <li><a href="#intervalos-de-predicci%C3%B3n" id="toc-intervalos-de-predicción" class="nav-link" data-scroll-target="#intervalos-de-predicci%C3%B3n"><span class="header-section-number">3.2.2</span> Intervalos de predicción</a></li>
  </ul>
</li>
  <li><a href="#suavizado-exponencial-doble-m%C3%A9todo-de-holt.-componentes-de-nivel-tendencia-y-error." id="toc-suavizado-exponencial-doble-método-de-holt.-componentes-de-nivel-tendencia-y-error." class="nav-link" data-scroll-target="#suavizado-exponencial-doble-m%C3%A9todo-de-holt.-componentes-de-nivel-tendencia-y-error."><span class="header-section-number">3.3</span> Suavizado exponencial doble (Método de Holt). Componentes de nivel, tendencia y error.</a></li>
  <li><a href="#triple-suavizado-exponencial-holt-winters.-componentes-de-nivel-tendencia-y-estacionalidad" id="toc-triple-suavizado-exponencial-holt-winters.-componentes-de-nivel-tendencia-y-estacionalidad" class="nav-link" data-scroll-target="#triple-suavizado-exponencial-holt-winters.-componentes-de-nivel-tendencia-y-estacionalidad"><span class="header-section-number">3.4</span> Triple suavizado exponencial (Holt-Winters). Componentes de nivel, tendencia y estacionalidad</a></li>
  <li><a href="#clasificaci%C3%B3n-de-pegels" id="toc-clasificación-de-pegels" class="nav-link" data-scroll-target="#clasificaci%C3%B3n-de-pegels"><span class="header-section-number">3.5</span> Clasificación de Pegels</a></li>
  <li><a href="#suavizado-exponencial-en-formato-de-espacio-de-los-estados" id="toc-suavizado-exponencial-en-formato-de-espacio-de-los-estados" class="nav-link" data-scroll-target="#suavizado-exponencial-en-formato-de-espacio-de-los-estados"><span class="header-section-number">3.6</span> Suavizado exponencial en formato de espacio de los estados</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">
<span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Suavizado Exponencial</span>
</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header><section id="suavizado-exponencial-simple.-componentes-de-nivel-y-error." class="level2" data-number="3.1"><h2 data-number="3.1" class="anchored" data-anchor-id="suavizado-exponencial-simple.-componentes-de-nivel-y-error.">
<span class="header-section-number">3.1</span> Suavizado exponencial simple. Componentes de nivel y error.</h2>
<p>En primer lugar, se asume que el patrón subyacente en la demanda es constante (al menos para los próximos días o semanas) con algunas fluctuaciones aleatorias alrededor del promedio, es decir, se supone que la serie temporal está formada por la combinación de los componentes de nivel y error aleatorio (<a href="#eq-nivel">Ecuación&nbsp;<span>3.1</span></a>). Por tanto, las técnicas de predicción que se verán en esta sección asumen el siguiente proceso generador de datos: <span id="eq-nivel"><span class="math display">\[
    y(t)= N + e
\tag{3.1}\]</span></span></p>
<section id="media-móvil" class="level3" data-number="3.1.1"><h3 data-number="3.1.1" class="anchored" data-anchor-id="media-móvil">
<span class="header-section-number">3.1.1</span> Media móvil</h3>
<p>Suaviza la demanda histórica promediando un número selecto de periodos pasados de datos y utiliza ese promedio como pronóstico para el siguiente periodo. El origen del modelo no es constante, sino que cada vez que se dispone de una nueva observación el origen del modelo se mueve con el fin de utilizar la historia más reciente para realizar las predicciones.</p>
<div id="fig-obser" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="obserpredic.jpg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figura&nbsp;3.1: Diferencia entre observaciones y pronósticos.</figcaption></figure>
</div>
<p>En la Figura <a href="#fig-obser">Figura&nbsp;<span>3.1</span></a> se muestra cómo se utilizan las observaciones (<span class="math inline">\(Y_1, Y_2, \ldots, Y_t\)</span>) hasta el origen (<span class="math inline">\(t\)</span>) para realizar los pronósticos para tiempos posteriores (<span class="math inline">\(F_{t+1}, F_{t+2},\ldots,\)</span>). De forma que, los pronósticos mediante la media móvil, se pueden calcular mediante la siguiente expresión: <span id="eq-MM1"><span class="math display">\[
    F_{t+1}=\sum_{t-n+1}^t \frac{Y_i}{n}
\tag{3.2}\]</span></span> donde <span class="math inline">\(i\)</span> es el número del periodo, <span class="math inline">\(t\)</span> es el periodo actual (el periodo para el cual la demanda real más reciente es conocida) y <span class="math inline">\(n\)</span> representa el número de periodos considerados en el promedio móvil. También se le conoce como <strong>orden</strong> de la media móvil. Otra expresión equivalente para calcular la predicción de la demanda para el periodo <span class="math inline">\(t+1\)</span> mediante una media móvil de orden <span class="math inline">\(n\)</span> es: <span id="eq-MM2"><span class="math display">\[
    F_{t+1}=F_t+ \frac{Y_t-Y_{t-n}}{n}
\tag{3.3}\]</span></span> Si comparamos la expresión <a href="#eq-MM1">Ecuación&nbsp;<span>3.2</span></a> con <a href="#eq-MM2">Ecuación&nbsp;<span>3.3</span></a> se puede observar que la última ecuación sólo necesita almacenar la última predicción (<span class="math inline">\(F_t\)</span>), la última observación (<span class="math inline">\(Y_t\)</span>) y la observación determinada por el orden de la media móvil (<span class="math inline">\(Y_{t-n}\)</span>). En cambio la primera ecuación tiene que almacenar todos los valores desde <span class="math inline">\(Y_{t-n+1}\)</span> hasta <span class="math inline">\(Y_t\)</span>. Además, en <a href="#eq-MM2">Ecuación&nbsp;<span>3.3</span></a> el número de operaciones que tiene que realizar para proporcionar una predicción es menor, lo que implica que es una expresión más eficiente desde el punto de vista computacional.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true">Resuelve</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">Solución</a></li>
</ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<p>Realiza una función en R que tenga como argumentos de entrada la serie temporal y el orden de la media móvil y, como argumento de salida, la predicción de la media móvil un paso hacia delante. Para comprobar que funciona correctamente, simula una normal aleatoria de tamaño 100 y un orden de media móvil de n=3. Dibuja la normal junto con las predicciones de la media móvil.</p>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/rm.html">rm</a></span><span class="op">(</span>list <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/ls.html">ls</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/message.html">suppressPackageStartupMessages</a></span><span class="op">(</span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st">"UComp"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/message.html">suppressPackageStartupMessages</a></span><span class="op">(</span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st"><a href="https://ggplot2.tidyverse.org">"ggplot2"</a></span><span class="op">)</span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">UComp</span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span></span>
<span><span class="va">mediamovil</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">y</span>, <span class="va">n</span><span class="op">=</span><span class="fl">1</span><span class="op">)</span><span class="op">{</span></span>
<span>    <span class="co"># dimension de la serie temporal</span></span>
<span>    <span class="va">dim</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">y</span><span class="op">)</span></span>
<span>    <span class="va">f</span><span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">0</span>,<span class="va">dim</span><span class="op">+</span><span class="fl">1</span><span class="op">)</span></span>
<span>    <span class="co">#Inicializo</span></span>
<span>    <span class="va">f</span><span class="op">[</span><span class="va">n</span><span class="op">+</span><span class="fl">1</span><span class="op">]</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">y</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="va">n</span><span class="op">]</span><span class="op">)</span></span>
<span>    <span class="co">#Calculo la media móvil recursiva</span></span>
<span>    <span class="kw">for</span> <span class="op">(</span><span class="va">t</span> <span class="kw">in</span> <span class="op">(</span><span class="va">n</span><span class="op">+</span><span class="fl">1</span><span class="op">)</span><span class="op">:</span> <span class="va">dim</span><span class="op">)</span><span class="op">{</span></span>
<span>    <span class="va">f</span><span class="op">[</span><span class="va">t</span><span class="op">+</span><span class="fl">1</span><span class="op">]</span><span class="op">&lt;-</span><span class="va">f</span><span class="op">[</span><span class="va">t</span><span class="op">]</span><span class="op">+</span><span class="op">(</span><span class="va">y</span><span class="op">[</span><span class="va">t</span><span class="op">]</span><span class="op">-</span><span class="va">y</span><span class="op">[</span><span class="va">t</span><span class="op">-</span><span class="va">n</span><span class="op">]</span><span class="op">)</span><span class="op">/</span><span class="va">n</span></span>
<span>    <span class="op">}</span></span>
<span>    <span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span><span class="op">(</span><span class="va">f</span><span class="op">)</span></span>
<span><span class="op">}</span></span>
<span><span class="co">#Simulo una normal</span></span>
<span><span class="va">data</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/ts.html">as.ts</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fl">100</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#Calculo su media movil de orden 3</span></span>
<span><span class="va">predMM</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/stats/ts.html">as.ts</a></span><span class="op">(</span><span class="fu">mediamovil</span><span class="op">(</span><span class="va">data</span>,<span class="fl">3</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#Lo dibujo</span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/autoplot.html">autoplot</a></span><span class="op">(</span><span class="va">predMM</span><span class="op">)</span><span class="op">+</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/autolayer.html">autolayer</a></span><span class="op">(</span><span class="va">data</span><span class="op">)</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="02-etsSSOE_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
</div>
</div>
<p>Al estar al final del periodo <span class="math inline">\(t\)</span>, se conoce la serie temporal en el periodo <span class="math inline">\(t\)</span> y los pronósticos se hacen para <span class="math inline">\(t+1\)</span>, o <span class="math inline">\(t+X\)</span> periodos en el futuro. No se hacen pronósticos para el periodo <span class="math inline">\(t\)</span> ya que la serie temporal de éste es conocida (ver <a href="#fig-obser">Figura&nbsp;<span>3.1</span></a> ). El método ingenuo (<strong>Naïve</strong>) es una media móvil para el caso particular de <span class="math inline">\(n=1\)</span>, el cual utiliza la última observación como predicción para el siguiente periodo. Este método ingenuo se utiliza como modelo de referencia cuando se propone una técnica de predicción, es decir, si alguien propone una técnica de predicción sofisticada para ciertos datos, estará justificada siempre y cuando mejore las predicciones proporcionadas por el método ingenuo.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true">Resuelve</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false">Solución Excel</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-3" role="tab" aria-controls="tabset-2-3" aria-selected="false">Solución R</a></li>
</ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<p>Las ventas de un disolvente químico son las mostradas en la tercera columna de la <a href="#tbl-enun">Tabla&nbsp;<span>3.1</span></a>, se pide calcular la predicción para el último mes mediante una media móvil de tercer orden y de quinto orden</p>
<div id="tbl-enun" class="anchored">
<table class="table">
<caption>Tabla&nbsp;3.1: Ventas mensuales disolvente</caption>
<thead><tr class="header">
<th>Mes</th>
<th>Periodo</th>
<th>Ventas</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Enero</td>
<td>1</td>
<td>200</td>
</tr>
<tr class="even">
<td>Febrero</td>
<td>2</td>
<td>135</td>
</tr>
<tr class="odd">
<td>Marzo</td>
<td>3</td>
<td>195</td>
</tr>
<tr class="even">
<td>Abril</td>
<td>4</td>
<td>197,5</td>
</tr>
<tr class="odd">
<td>Mayo</td>
<td>5</td>
<td>310</td>
</tr>
<tr class="even">
<td>Junio</td>
<td>6</td>
<td>175</td>
</tr>
<tr class="odd">
<td>Julio</td>
<td>7</td>
<td>155</td>
</tr>
<tr class="even">
<td>Agosto</td>
<td>8</td>
<td>130</td>
</tr>
<tr class="odd">
<td>Septiembre</td>
<td>9</td>
<td>220</td>
</tr>
<tr class="even">
<td>Octubre</td>
<td>10</td>
<td>277,5</td>
</tr>
<tr class="odd">
<td>Noviembre</td>
<td>11</td>
<td>235</td>
</tr>
<tr class="even">
<td>Diciembre</td>
<td>12</td>
<td>?</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<p>Si aplicamos la ecuación <a href="#eq-MM1">Ecuación&nbsp;<span>3.2</span></a> para <span class="math inline">\(n=3\)</span> y <span class="math inline">\(n=5\)</span> podemos obtener las predicciones solicitadas para el mes de diciembre, ver <a href="#tbl-sol1">Tabla&nbsp;<span>3.2</span></a> . La cuarta y quinta columna en la Tabla muestran las predicciones obtenidas para una media móvil de orden 3 y 5, respectivamente.</p>
<div id="tbl-sol1" class="anchored">
<table class="table">
<caption>Tabla&nbsp;3.2: Ventas mensuales disolvente y predicciones</caption>
<colgroup>
<col style="width: 17%">
<col style="width: 13%">
<col style="width: 11%">
<col style="width: 28%">
<col style="width: 28%">
</colgroup>
<thead><tr class="header">
<th>Mes</th>
<th>Periodo</th>
<th>Ventas</th>
<th>Media Móvil (n=3)</th>
<th>Media Móvil (n=5)</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Enero</td>
<td>1</td>
<td>200</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Febrero</td>
<td>2</td>
<td>135</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Marzo</td>
<td>3</td>
<td>195</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Abril</td>
<td>4</td>
<td>197,5</td>
<td>176,7</td>
<td></td>
</tr>
<tr class="odd">
<td>Mayo</td>
<td>5</td>
<td>310</td>
<td>175,8</td>
<td></td>
</tr>
<tr class="even">
<td>Junio</td>
<td>6</td>
<td>175</td>
<td>234,2</td>
<td>207,5</td>
</tr>
<tr class="odd">
<td>Julio</td>
<td>7</td>
<td>155</td>
<td>227,5</td>
<td>202,5</td>
</tr>
<tr class="even">
<td>Agosto</td>
<td>8</td>
<td>130</td>
<td>213,3</td>
<td>206,5</td>
</tr>
<tr class="odd">
<td>Septiembre</td>
<td>9</td>
<td>220</td>
<td>153,3</td>
<td>193,5</td>
</tr>
<tr class="even">
<td>Octubre</td>
<td>10</td>
<td>277,5</td>
<td>168,3</td>
<td>198</td>
</tr>
<tr class="odd">
<td>Noviembre</td>
<td>11</td>
<td>235</td>
<td>209,2</td>
<td>191,5</td>
</tr>
<tr class="even">
<td>Diciembre</td>
<td>12</td>
<td>?</td>
<td>244,2</td>
<td>203,5</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="tabset-2-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-3-tab">
<p>En construcción</p>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Borramos memoria</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/rm.html">rm</a></span><span class="op">(</span>list <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/ls.html">ls</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/message.html">suppressPackageStartupMessages</a></span><span class="op">(</span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st"><a href="https://ggplot2.tidyverse.org">"ggplot2"</a></span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/message.html">suppressPackageStartupMessages</a></span><span class="op">(</span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st">"UComp"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co"># Cargamos librerías</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">UComp</span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span></span>
<span><span class="co"># Recuperamos la función media móvil</span></span>
<span><span class="va">mediamovil</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">y</span>, <span class="va">n</span><span class="op">=</span><span class="fl">1</span><span class="op">)</span><span class="op">{</span></span>
<span>    <span class="co"># dimension de la serie temporal</span></span>
<span>    <span class="va">dim</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">y</span><span class="op">)</span></span>
<span>    <span class="va">f</span><span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">0</span>,<span class="va">dim</span><span class="op">+</span><span class="fl">1</span><span class="op">)</span></span>
<span>    <span class="co">#Inicializo</span></span>
<span>    <span class="va">f</span><span class="op">[</span><span class="va">n</span><span class="op">+</span><span class="fl">1</span><span class="op">]</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">y</span><span class="op">[</span><span class="fl">1</span><span class="op">:</span><span class="va">n</span><span class="op">]</span><span class="op">)</span></span>
<span>    <span class="co">#Calculo la media móvil recursiva</span></span>
<span>    <span class="kw">for</span> <span class="op">(</span><span class="va">t</span> <span class="kw">in</span> <span class="op">(</span><span class="va">n</span><span class="op">+</span><span class="fl">1</span><span class="op">)</span><span class="op">:</span> <span class="va">dim</span><span class="op">)</span><span class="op">{</span></span>
<span>    <span class="va">f</span><span class="op">[</span><span class="va">t</span><span class="op">+</span><span class="fl">1</span><span class="op">]</span><span class="op">&lt;-</span><span class="va">f</span><span class="op">[</span><span class="va">t</span><span class="op">]</span><span class="op">+</span><span class="op">(</span><span class="va">y</span><span class="op">[</span><span class="va">t</span><span class="op">]</span><span class="op">-</span><span class="va">y</span><span class="op">[</span><span class="va">t</span><span class="op">-</span><span class="va">n</span><span class="op">]</span><span class="op">)</span><span class="op">/</span><span class="va">n</span></span>
<span>    <span class="op">}</span></span>
<span>    <span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span><span class="op">(</span><span class="va">f</span><span class="op">)</span></span>
<span><span class="op">}</span></span>
<span><span class="co">#Cargamos los datos</span></span>
<span><span class="va">y</span><span class="op">&lt;-</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/ts.html">ts</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">200</span>,<span class="fl">135</span>,<span class="fl">195</span>,<span class="fl">197.5</span>,<span class="fl">310</span>,<span class="fl">175</span>,<span class="fl">155</span>,<span class="fl">130</span>,<span class="fl">220</span>,<span class="fl">277.5</span>,<span class="fl">235</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">mm3</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/stats/ts.html">as.ts</a></span><span class="op">(</span><span class="fu">mediamovil</span><span class="op">(</span><span class="va">y</span>,<span class="fl">3</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">mm5</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/stats/ts.html">as.ts</a></span><span class="op">(</span><span class="fu">mediamovil</span><span class="op">(</span><span class="va">y</span>,<span class="fl">5</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/autoplot.html">autoplot</a></span><span class="op">(</span><span class="va">y</span><span class="op">)</span><span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/autolayer.html">autolayer</a></span><span class="op">(</span><span class="va">mm3</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/autolayer.html">autolayer</a></span><span class="op">(</span><span class="va">mm5</span><span class="op">)</span> <span class="op">+</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>title <span class="op">=</span> <span class="st">"Ventas mensuales"</span><span class="op">)</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="02-etsSSOE_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
</div>
</div>
<p>En el ejemplo anterior, se han realizado unas predicciones basadas en las medias móviles de diferente orden. No obstante, uno podría preguntarse, ¿cómo se define el orden de la media móvil? o lo que es lo mismo ¿qué valor de <em>n</em> elijo para realizar mis predicciones? Para determinar el valor de <em>n</em>, se tendrían que calcular los errores de predicción y seleccionar aquel valor de <em>n</em> que los minimice. Como todavía no se han definido los errores de predicción, dejaremos para más adelante en este capítulo como llevar a cabo dicha optimización. De momento, aunque no sepamos cómo elegir <em>n</em> de forma óptima si es recomendable que se entienda el efecto del parámetro de diseño <em>n</em>. Para ello pondremos el siguiente ejemplo. En la <a href="#fig-MM">Figura&nbsp;<span>3.2</span></a> se ha representado una serie temporal <em>y(t)</em> la cuál queremos predecir. Con ese fin, se han calculado medias móviles con los siguientes valores de <em>n</em>, <em>n=10, 50.</em> ¿Podrías explicar cuál ha sido el efecto de aumentar el valor de <em>n</em>? En principio hay dos efectos muy claros. El primero es que cuanto mayor es el valor de <em>n</em>, más observaciones se requieren para poder empezar a realizar predicciones. El segundo efecto, es que cuanto mayor es el valor de <em>n</em> mayor es el suavizado de nuestras predicciones. Estas mismas conclusiones se pueden observar en el primer ejemplo en la <a href="#fig-MM">Figura&nbsp;<span>3.2</span></a>. De acuerdo a estas conclusiones iniciales uno podría pensar que la mejor decisión será elegir un orden lo mayor posible para conseguir un mayor grado de suavizado. No obstante esta decisión también tiene sus inconvenientes. Si repetimos el mismo experimento anterior, pero en este caso sobre la serie temporal mostrada en la <a href="#fig-MM2">Figura&nbsp;<span>3.3</span></a>, se puede observar que la media móvil de orden (<span class="math inline">\(n=50\)</span>) es incapaz de adaptarse al salto brusco que ha ocurrido en los datos, mientras que la media móvil de menor orden (<span class="math inline">\(n=10\)</span>) se adapta mucho más rápido. Por tanto, cuanto mayor sea el orden de la media móvil, mayor será su suavizado pero menor será su capacidad de adaptación a cambios bruscos en la serie temporal.</p>
<div id="fig-MM" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="ejemplo2mediamovil.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figura&nbsp;3.2: Efecto de suavizado del parámetro <em>n</em>.</figcaption></figure>
</div>
<div id="fig-MM2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="ejemplo2mediamovil2.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figura&nbsp;3.3: Efecto del parámetro <em>n</em> sobre la capacidad de adaptación a cambios bruscos.</figcaption></figure>
</div>
</section><section id="suavizado-exponencial" class="level3" data-number="3.1.2"><h3 data-number="3.1.2" class="anchored" data-anchor-id="suavizado-exponencial">
<span class="header-section-number">3.1.2</span> Suavizado exponencial</h3>
<p>El algoritmo de suavizado exponencial fue inicialmente propuesto por Robert Brown sobre 1944, cuando estuvo trabajando como analista de investigación de operaciones en la marina de los EEUU, donde implementó esta idea en un aparato mecánico con el fin de rastrear la velocidad y ángulo utilizados para derribar submarinos. Otra de sus primeras aplicaciones fue pronosticar la necesidad de piezas de repuesto en el sistema de inventarios de la marina de los EEUU. Posteriormente, sobre 1950 extendió sus resultados para incluir componentes de tendencia y estacionalidad. Es interesante señalar que, independientemente, Charles Holt que trabajaba en la oficina de investigación naval desarrolló también un suavizado exponencial incluyendo las componentes de tendencia y estacionalidad.</p>
<p>Al igual que la media móvil, el suavizado exponencial se utiliza cuando las componentes principales en la serie temporal son el nivel y el error aleatorio. Si analizamos el ejemplo 1 de la sección anterior, se puede comprobar que la media móvil suaviza los datos históricos ponderando con un mismo peso cada observación del histórico de datos. De forma que si volvemos a calcular la media móvil de orden 3 del ejemplo anterior, teníamos que: <span class="math display">\[
\begin{equation}
    F_{12}=\frac{220 + 277.5 + 235}{3}=244.2
\end{equation}
\]</span> donde el peso de cada observación sería <span class="math inline">\(1/3\)</span>. No obstante, uno podría pensar que tendría más sentido que lo que ha pasado ayer afecte más a lo que pase mañana, que lo que ocurrió hace 2 semanas, o dicho en otras palabras, que los pesos más cercanos al presente sean mayores que los pesos más alejados del presente.</p>
<p>En este apartado se describe el suavizado exponencial que, siguiendo esa lógica, coloca los pesos en las observaciones de manera que decrecen exponencialmente según las observaciones se alejan del presente. El pronóstico por suavizado exponencial se calcula como: <span id="eq-SE2"><span class="math display">\[
\begin{eqnarray}
    F_{t+1}&amp;=&amp;F_t + \alpha(Y_t - F_t)  \\
    F_{t+1}&amp;=&amp;\alpha(Y_t) + (1-\alpha)F_t    
\end{eqnarray}
\tag{3.4}\]</span></span> donde <span class="math inline">\(\alpha\)</span> es una constante positiva entre 0 y 1. Se puede observar que la nueva predicción es simplemente la predicción anterior más un ajuste de los errores de predicción que ocurrieron en el periodo anterior. Cuando <span class="math inline">\(\alpha\)</span> tiene un valor cercano a 1, el nuevo pronóstico incluirá un ajuste sustancial debido al error en el pronóstico anterior. Sin embargo, si tiene una valor cercano a 0, el nuevo pronóstico no se ajustará mucho. Las implicaciones del suavizado exponencial se pueden ver mejor si expandimos la ecuación anterior: <span id="eq-sesexpandido"><span class="math display">\[
\begin{eqnarray}
F_{t+1}&amp;=&amp;\alpha Y_t + \alpha (1-\alpha)Y_{t-1} + \alpha(1-\alpha)^2Y_{t-2}+ \alpha(1-\alpha)^3Y_{t-3} \nonumber \\
&amp;&amp;+\alpha(1-\alpha)^4Y_{t-4}+\ldots+(1-\alpha)^{t}F_1   
\end{eqnarray}
\tag{3.5}\]</span></span> La <a href="#eq-sesexpandido">Ecuación&nbsp;<span>3.5</span></a> muestra como se distribuyen los pesos en las observaciones pasadas, de modo que si <span class="math inline">\(\alpha\)</span> es menor que 1, dicho peso decrece exponencialmente. Es interesante señalar el último término de dicha expresión <span class="math inline">\((1-\alpha)^{t}F_1\)</span>, donde <span class="math inline">\(F_1\)</span> es la predicción inicial, la cuál desconocemos y tenemos que estimar. La estimación de dicho valor se le conoce como <strong>inicialización</strong> del algoritmo.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-3-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-1" role="tab" aria-controls="tabset-3-1" aria-selected="true">Resuelve</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-2" role="tab" aria-controls="tabset-3-2" aria-selected="false">Solución</a></li>
</ul>
<div class="tab-content">
<div id="tabset-3-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-3-1-tab">
<p>Supongamos que <span class="math inline">\(\alpha=0,3\)</span> y <span class="math inline">\(t=3\)</span>, ¿Cuál es el peso que tendrá la predicción inicial <span class="math inline">\(F_1\)</span>?</p>
</div>
<div id="tabset-3-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-2-tab">
<p><span class="math display">\[
F_4=0.3Y_3+0.21Y_2+0.147Y_1+0.343F_1
\]</span> Se puede observar que el peso de la predicción inicial <span class="math inline">\(F_1\)</span> es igual a 0.343 que es incluso superior al peso de la observación más reciente <span class="math inline">\(Y_3\)</span> que es 0.3. Por tanto, hay que ser conscientes que si disponemos de pocas observaciones el peso de la predicción inicial es muy significativo y, por tanto, es crucial estimar adecuadamente <span class="math inline">\(F_1\)</span>.</p>
</div>
</div>
</div>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-4-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-1" role="tab" aria-controls="tabset-4-1" aria-selected="true">Resuelve</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-4-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-4-2" role="tab" aria-controls="tabset-4-2" aria-selected="false">Solución</a></li>
</ul>
<div class="tab-content">
<div id="tabset-4-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-4-1-tab">
<p>Para el mismo valor de <span class="math inline">\(\alpha\)</span> del ejercicio anterior, ¿cuál sería el peso de <span class="math inline">\(F_1\)</span> si t=20? Para resolverlo, programa una función que calcule los pesos en función del valor de <span class="math inline">\(\alpha\)</span> y <span class="math inline">\(t\)</span>. Dibuja la evolución de dichos pesos frente al tiempo.</p>
</div>
<div id="tabset-4-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-4-2-tab">
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Borramos memoria</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/rm.html">rm</a></span><span class="op">(</span>list <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/ls.html">ls</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/message.html">suppressPackageStartupMessages</a></span><span class="op">(</span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st"><a href="https://ggplot2.tidyverse.org">"ggplot2"</a></span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/message.html">suppressPackageStartupMessages</a></span><span class="op">(</span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st">"UComp"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co"># Cargamos librerías</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">UComp</span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span></span>
<span><span class="co"># Recuperamos la función media móvil</span></span>
<span><span class="va">sespesos</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">t</span><span class="op">=</span><span class="fl">10</span>, <span class="va">a</span><span class="op">=</span><span class="fl">0.1</span><span class="op">)</span><span class="op">{</span></span>
<span>    <span class="va">peso</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">0</span>,<span class="va">t</span><span class="op">+</span><span class="fl">1</span><span class="op">)</span></span>
<span>    <span class="kw">for</span> <span class="op">(</span><span class="va">i</span> <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="op">(</span><span class="va">t</span><span class="op">)</span> <span class="op">)</span> <span class="op">{</span></span>
<span>    <span class="co">#Calculo la media móvil recursiva</span></span>
<span>    <span class="va">peso</span><span class="op">[</span><span class="va">i</span><span class="op">]</span><span class="op">&lt;-</span><span class="va">a</span><span class="op">*</span><span class="op">(</span><span class="fl">1</span><span class="op">-</span><span class="va">a</span><span class="op">)</span><span class="op">^</span><span class="op">(</span><span class="va">i</span><span class="op">-</span><span class="fl">1</span><span class="op">)</span></span>
<span>    <span class="op">}</span></span>
<span>    <span class="co">#Le añado el peso de la condición inicial</span></span>
<span>    <span class="va">peso</span><span class="op">[</span><span class="va">t</span><span class="op">+</span><span class="fl">1</span><span class="op">]</span><span class="op">&lt;-</span><span class="op">(</span><span class="fl">1</span><span class="op">-</span><span class="va">a</span><span class="op">)</span><span class="op">^</span><span class="va">t</span></span>
<span>    <span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span><span class="op">(</span><span class="va">peso</span><span class="op">)</span></span>
<span><span class="op">}</span></span>
<span><span class="va">pesos</span><span class="op">&lt;-</span><span class="fu">sespesos</span><span class="op">(</span><span class="fl">20</span>,<span class="fl">0.3</span><span class="op">)</span></span>
<span><span class="va">d1</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>tiempo<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">21</span><span class="op">)</span>,<span class="va">pesos</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">d1</span>,mapping <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">tiempo</span>, y<span class="op">=</span><span class="va">pesos</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_x_continuous</a></span><span class="op">(</span>breaks<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">21</span><span class="op">)</span>,labels<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="st">"Y"</span>,<span class="fl">20</span><span class="op">:</span><span class="fl">1</span>,sep<span class="op">=</span><span class="st">""</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="st">"F"</span>,<span class="fl">1</span>,sep<span class="op">=</span><span class="st">""</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="02-etsSSOE_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>En este caso, el peso sería aproximadamente cero, es decir, cuando disponemos de más observaciones las predicciones iniciales tienen muy poco peso.</p>
</div>
</div>
</div>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-5-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-1" role="tab" aria-controls="tabset-5-1" aria-selected="true">Resuelve</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-5-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-5-2" role="tab" aria-controls="tabset-5-2" aria-selected="false">Solución</a></li>
</ul>
<div class="tab-content">
<div id="tabset-5-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-5-1-tab">
<p>Para el mismo valor de <span class="math inline">\(t=20\)</span> del ejercicio anterior, ¿qué ocurriría para diferentes valores de <span class="math inline">\(\alpha=0.2, 0.3, 0.7\)</span>? Dibuja la evolución de dichos pesos frente al tiempo.</p>
</div>
<div id="tabset-5-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-5-2-tab">
<div class="cell">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Borramos memoria</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/rm.html">rm</a></span><span class="op">(</span>list <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/ls.html">ls</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/message.html">suppressPackageStartupMessages</a></span><span class="op">(</span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st"><a href="https://ggplot2.tidyverse.org">"ggplot2"</a></span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/message.html">suppressPackageStartupMessages</a></span><span class="op">(</span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st">"UComp"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/message.html">suppressPackageStartupMessages</a></span><span class="op">(</span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st"><a href="https://www.stefanom.io/latex2exp/">"latex2exp"</a></span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co"># Cargamos librerías</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">UComp</span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://www.stefanom.io/latex2exp/">latex2exp</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Recuperamos la función media móvil</span></span>
<span><span class="va">sespesos</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">t</span><span class="op">=</span><span class="fl">10</span>, <span class="va">a</span><span class="op">=</span><span class="fl">0.1</span><span class="op">)</span><span class="op">{</span></span>
<span>    <span class="va">peso</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">0</span>,<span class="va">t</span><span class="op">+</span><span class="fl">1</span><span class="op">)</span></span>
<span>    <span class="kw">for</span> <span class="op">(</span><span class="va">i</span> <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="op">(</span><span class="va">t</span><span class="op">)</span> <span class="op">)</span> <span class="op">{</span></span>
<span>    <span class="co">#Calculo la media móvil recursiva</span></span>
<span>    <span class="va">peso</span><span class="op">[</span><span class="va">i</span><span class="op">]</span><span class="op">&lt;-</span><span class="va">a</span><span class="op">*</span><span class="op">(</span><span class="fl">1</span><span class="op">-</span><span class="va">a</span><span class="op">)</span><span class="op">^</span><span class="op">(</span><span class="va">i</span><span class="op">-</span><span class="fl">1</span><span class="op">)</span></span>
<span>    <span class="op">}</span></span>
<span>    <span class="co">#Le añado el peso de la condición inicial</span></span>
<span>    <span class="va">peso</span><span class="op">[</span><span class="va">t</span><span class="op">+</span><span class="fl">1</span><span class="op">]</span><span class="op">&lt;-</span><span class="op">(</span><span class="fl">1</span><span class="op">-</span><span class="va">a</span><span class="op">)</span><span class="op">^</span><span class="va">t</span></span>
<span>    <span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span><span class="op">(</span><span class="va">peso</span><span class="op">)</span></span>
<span><span class="op">}</span></span>
<span><span class="va">pesos1</span><span class="op">&lt;-</span><span class="fu">sespesos</span><span class="op">(</span><span class="fl">20</span>,<span class="fl">0.2</span><span class="op">)</span></span>
<span><span class="va">pesos2</span><span class="op">&lt;-</span><span class="fu">sespesos</span><span class="op">(</span><span class="fl">20</span>,<span class="fl">0.3</span><span class="op">)</span></span>
<span><span class="va">pesos3</span><span class="op">&lt;-</span><span class="fu">sespesos</span><span class="op">(</span><span class="fl">20</span>,<span class="fl">0.7</span><span class="op">)</span></span>
<span><span class="va">d1</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>tiempo<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">21</span><span class="op">)</span>,<span class="fl">3</span><span class="op">)</span>,pesos<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">pesos1</span>,<span class="va">pesos2</span>,<span class="va">pesos3</span><span class="op">)</span>,alpha<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">0.2</span>,<span class="fl">21</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">0.3</span>,<span class="fl">21</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">0.7</span>,<span class="fl">21</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">d1</span>,<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">tiempo</span>, y<span class="op">=</span><span class="va">pesos</span>, group<span class="op">=</span><span class="va">alpha</span>, color<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span><span class="va">alpha</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_x_continuous</a></span><span class="op">(</span>breaks<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">21</span><span class="op">)</span>,<span class="fl">3</span><span class="op">)</span>,labels<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="st">"Y"</span>,<span class="fl">20</span><span class="op">:</span><span class="fl">1</span>,sep<span class="op">=</span><span class="st">""</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="st">"F"</span>,<span class="fl">1</span>,sep<span class="op">=</span><span class="st">""</span><span class="op">)</span><span class="op">)</span>,<span class="fl">3</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x<span class="op">=</span><span class="st">"Observaciones"</span>, y<span class="op">=</span><span class="st">"Pesos"</span>, color<span class="op">=</span><span class="fu"><a href="https://www.stefanom.io/latex2exp/reference/TeX.html">TeX</a></span><span class="op">(</span><span class="st">"$\\alpha$"</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-efectoalpha" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="02-etsSSOE_files/figure-html/fig-efectoalpha-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figura&nbsp;3.4: Efecto del parámetro alpha sobre los pesos del suavizado exponencial.</figcaption></figure>
</div>
</div>
</div>
<p>La <a href="#fig-efectoalpha">Figura&nbsp;<span>3.4</span></a> muestra la influencia del parámetro <span class="math inline">\(\alpha\)</span> sobre el peso de las observaciones. En dicha figura se puede observar que cuanto más cercano a 1 se encuentra el parámetro <span class="math inline">\(\alpha\)</span>, más peso se le dan a las observaciones más recientes y viceversa.</p>
</div>
</div>
</div>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-6-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-1" role="tab" aria-controls="tabset-6-1" aria-selected="true">Resuelve</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-6-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-6-2" role="tab" aria-controls="tabset-6-2" aria-selected="false">Solución</a></li>
</ul>
<div class="tab-content">
<div id="tabset-6-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-6-1-tab">
<p>Una bodega en la Mancha ha exportado grandes cantidades de vino de calidad suprema durante los ocho últimos trimestres que se muestran en la segunda columna de la <a href="#tbl-bodega">Tabla&nbsp;<span>3.3</span></a>. El director de operaciones quiere analizar la utilización de la técnica de suavizado exponencial en la previsión de las cajas de botellas exportadas. Para ello, supone que la previsión de vino exportado en el primer trimestre fue de 1.750 cajas. Se plantea utilizar los siguientes valores <span class="math inline">\(\alpha=0,1\)</span> y <span class="math inline">\(0,5\)</span>. ¿Cuál será la previsión para el trimestre 9?</p>
<div id="tbl-bodega" class="anchored">
<table class="table">
<caption>Tabla&nbsp;3.3: Ventas trimestrales de la bodega</caption>
<thead><tr class="header">
<th><strong>Trimestre</strong></th>
<th><strong>Ventas</strong></th>
</tr></thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>1.800</td>
</tr>
<tr class="even">
<td>2</td>
<td>1.700</td>
</tr>
<tr class="odd">
<td>3</td>
<td>1.590</td>
</tr>
<tr class="even">
<td>4</td>
<td>1.600</td>
</tr>
<tr class="odd">
<td>5</td>
<td>1.800</td>
</tr>
<tr class="even">
<td>6</td>
<td>2.000</td>
</tr>
<tr class="odd">
<td>7</td>
<td>1.850</td>
</tr>
<tr class="even">
<td>8</td>
<td>1.820</td>
</tr>
<tr class="odd">
<td>9</td>
<td><strong>?</strong></td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="tabset-6-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-6-2-tab">
<div class="cell">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Borramos memoria</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/rm.html">rm</a></span><span class="op">(</span>list <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/ls.html">ls</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/message.html">suppressPackageStartupMessages</a></span><span class="op">(</span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st"><a href="https://ggplot2.tidyverse.org">"ggplot2"</a></span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/message.html">suppressPackageStartupMessages</a></span><span class="op">(</span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st">"UComp"</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Cargamos librerías</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">UComp</span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co">#Programo una función que calcule el suavizado exponencial simple</span></span>
<span><span class="va">ses</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">y</span>, <span class="va">a</span><span class="op">=</span><span class="fl">0.03</span><span class="op">)</span><span class="op">{</span></span>
<span>    <span class="va">t</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">y</span><span class="op">)</span></span>
<span>    <span class="va">f</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fl">0</span>,<span class="va">t</span><span class="op">+</span><span class="fl">1</span><span class="op">)</span></span>
<span>    <span class="co">#Inicializo</span></span>
<span>    <span class="va">f</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span><span class="op">&lt;-</span><span class="va">y</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span></span>
<span>    <span class="co"># Recorremos el vector y</span></span>
<span>    <span class="kw">for</span> <span class="op">(</span><span class="va">i</span> <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="op">(</span><span class="va">t</span><span class="op">)</span> <span class="op">)</span> <span class="op">{</span></span>
<span>    <span class="co">#Calculo la media móvil recursiva</span></span>
<span>    <span class="va">f</span><span class="op">[</span><span class="va">i</span><span class="op">+</span><span class="fl">1</span><span class="op">]</span><span class="op">&lt;-</span><span class="va">f</span><span class="op">[</span><span class="va">i</span><span class="op">]</span><span class="op">+</span><span class="va">a</span><span class="op">*</span><span class="op">(</span><span class="va">y</span><span class="op">[</span><span class="va">i</span><span class="op">]</span><span class="op">-</span><span class="va">f</span><span class="op">[</span><span class="va">i</span><span class="op">]</span><span class="op">)</span></span>
<span>    <span class="op">}</span></span>
<span>    <span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span><span class="op">(</span><span class="va">f</span><span class="op">)</span></span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="va">ventas</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1800</span>,<span class="fl">1700</span>,<span class="fl">1590</span>,<span class="fl">1600</span>,<span class="fl">1800</span>,<span class="fl">2000</span>,<span class="fl">1850</span>,<span class="fl">1820</span><span class="op">)</span></span>
<span></span>
<span><span class="va">pred1</span><span class="op">&lt;-</span><span class="fu">ses</span><span class="op">(</span><span class="va">ventas</span>,<span class="fl">0.1</span><span class="op">)</span></span>
<span><span class="va">pred2</span><span class="op">&lt;-</span><span class="fu">ses</span><span class="op">(</span><span class="va">ventas</span>,<span class="fl">0.5</span><span class="op">)</span></span>
<span></span>
<span><span class="co">#Dibujamos los resultados</span></span>
<span><span class="va">dv</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>tiempo<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">ventas</span><span class="op">)</span><span class="op">)</span>,<span class="va">ventas</span><span class="op">)</span></span>
<span><span class="va">d1</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>tiempo<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">9</span><span class="op">)</span>,<span class="fl">2</span><span class="op">)</span>,<span class="fl">1</span><span class="op">:</span><span class="fl">8</span><span class="op">)</span>,pred<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">pred1</span>,<span class="va">pred2</span>,<span class="va">ventas</span><span class="op">)</span>,alpha<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"alpha=0.1"</span>,<span class="fl">9</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"alpha=0.5"</span>,<span class="fl">9</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">'Ventas'</span>,<span class="fl">8</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">d1</span>,<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">tiempo</span>, y<span class="op">=</span><span class="va">pred</span>, group<span class="op">=</span><span class="va">alpha</span>, color<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span><span class="va">alpha</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">d1</span>,<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">tiempo</span>, y<span class="op">=</span><span class="va">pred</span>, group<span class="op">=</span><span class="va">alpha</span>, color<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span><span class="va">alpha</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x<span class="op">=</span><span class="st">"Observaciones"</span>, y<span class="op">=</span><span class="st">"Predicciones"</span>, color<span class="op">=</span><span class="st">"Leyenda"</span><span class="op">)</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="02-etsSSOE_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>En la figura se muestran las cajas descargadas junto con las previsiones utilizando un suavizado exponencial simple para los dos valores de <span class="math inline">\(\alpha\)</span> considerados. Se puede observar que un valor del <span class="math inline">\(\alpha\)</span> más cercano a 0 proporciona un mayor suavizado en las predicciones.</p>
</div>
</div>
</div>
<p>Hasta ahora hemos supuesto que el valor de la predicción inicial <span class="math inline">\(F_1\)</span> era un dato conocido. No obstante, en la realidad dicha predicción inicial no es conocida sino que hay que estimarla. Una solución <em>heurística</em> común es usar la primera observación como pronóstico inicial (<span class="math inline">\(F_1=Y_1\)</span>). Otra posibilidad más robusta es promediar los tres, cuatro primeros valores y usar ese promedio como pronóstico inicial, tal que:</p>
<p><span class="math display">\[
    F_1=\frac{Y_1+Y_2+Y_3}{3}
\]</span></p>
</section></section><section id="evaluación-de-las-predicciones" class="level2" data-number="3.2"><h2 data-number="3.2" class="anchored" data-anchor-id="evaluación-de-las-predicciones">
<span class="header-section-number">3.2</span> Evaluación de las predicciones</h2>
<p>En la <a href="#fig-caravaggio">Figura&nbsp;<span>3.5 (1)</span></a> se muestra una pintura de Caravaggio localizada en el museo del Louvre de París: <em>La buenaventura</em>, 1595. El cuadro muestra a un joven vestido con ropas elegantes al que una chica <em>pobre</em> lee la palma de la mano. El chico parece encantado al mirarle a la cara (no se da cuenta de que ella está quitándole poco a poco el anillo) a esta mirada masculina ella responde con su propia mirada astuta y silenciosa. La atención del espectador se centra precisamente en esas miradas que permiten adivinar lo que cada uno de los personajes piensan, en lugar de lo que ocurre en las dos manos de los personajes.</p>
<p>Este cuadro se menciona en el libro del cisne negro de Nassim Taleb para mostrarnos cuán ingenuos podemos llegar a ser frente a aquellos que nos cuentan el futuro. Para no ser tomados como ingenuos, necesitaremos ser críticos con las predicciones a las que nos tengamos que enfrentar. Para ello una herramienta muy útil es conocer el error de predicción. De forma que cuando alguien nos presente una estimación para no ser tomados por ingenuos también deberíamos exigir cuál es el error de dicha estimación. Por ejemplo, no es lo mismo decir nuestra previsión de ventas para el mes siguiente es de 1000 unidades más/menos 10 que tener una previsión de 1000 unidades más/menos 500.</p>
<p>Otro cuadro que muestra el interés de conocer el futuro se muestra en <a href="#fig-julioromero">Figura&nbsp;<span>3.5 (2)</span></a>. Dicho cuadro de Julio Romero (1920) se muestra en el museo Thyssen de Málaga (https://www.carmenthyssenmalaga.org/obra/la-buenaventura)</p>
<div id="fig-cuadros" class="quarto-layout-panel">
<figure class="figure"><div class="quarto-layout-row quarto-layout-valign-top">
<div class="quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-caravaggio" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="caravaggio.jpg" class="img-fluid figure-img" data-ref-parent="fig-cuadros"></p>
<figcaption class="figure-caption">(1) La buenaventura de Caravaggio.</figcaption></figure>
</div>
</div>
<div class="quarto-layout-cell quarto-layout-cell-subref" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-julioromero" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="labuenaventurajulio.jpg" class="img-fluid figure-img" data-ref-parent="fig-cuadros"></p>
<figcaption class="figure-caption">(2) La buenaventura de Julio Romero de Torres.</figcaption></figure>
</div>
</div>
</div>
<p></p><figcaption class="figure-caption">Figura&nbsp;3.5: Cuadros representando el interés de los humanos por conocer el futuro.</figcaption><p></p>
</figure>
</div>
<p>En resumen, el ejercicio de previsión no finaliza una vez realizadas las predicciones sino que tenemos que comprobar que dichas previsiones son adecuadas. Para ello es importante estimar los errores de predicción. Además, el análisis de los errores nos permite:</p>
<ul>
<li>Detectar indicadores de demandas erráticas que deben evaluarse con cuidado y quizás eliminar de los datos.</li>
<li>Estimar los parámetros de los algoritmos mediante la minimización de los errores de predicción.</li>
<li>Determinar cuando el método de pronóstico no representa ya la demanda actual y es necesario volver a proponer diferentes modelos.</li>
</ul>
<section id="medidas-de-error-de-predicción" class="level3" data-number="3.2.1"><h3 data-number="3.2.1" class="anchored" data-anchor-id="medidas-de-error-de-predicción">
<span class="header-section-number">3.2.1</span> Medidas de error de predicción</h3>
<p>Independientemente de si se utilizan métodos o modelos formales para realizar la predicción de cualquier variable, algo que nos va a interesar siempre es comprobar la calidad de las predicciones, su nivel de precisión e incluso comparar la precisión de distintos métodos para las mismas series, con el fin de elegir el mejor.</p>
<p>Denotamos por <span class="math inline">\(\hat{y}_{T+l|T}\)</span> a la predicción de la variable <span class="math inline">\(y_t\)</span>, <span class="math inline">\(l\)</span> periodos hacia adelante con origen de predicción <span class="math inline">\(T\)</span>. El <strong>error de predicción</strong> <span class="math inline">\(l\)</span> <strong>periodos hacia adelante con origen</strong> <span class="math inline">\(T\)</span> se define como la diferencia entre la predicción y el valor real, tal que:</p>
<p><span class="math display">\[\hat{e}_{T+l|T}=\hat{y}_{T+l|T}-y_{T+l}\]</span></p>
<p>A la hora de definir las métricas hay que distinguir dos conceptos: a) el sesgo del error; y b) la precisión del error.</p>
<p>El <strong>sesgo</strong> nos indica el error sistemático de las predicciones, es decir, si las predicciones son superiores o inferiores a los valores reales. Evidentemente, para predicciones individuales el error nunca será exactamente cero, pero lo ideal es que los errores positivos se compensen con errores negativos. Por tanto, las medidas de sesgo tienen asociado un signo positivo o negativo. La métrica más conocida es el ME (ver <a href="#tbl-sesgo">Tabla&nbsp;<span>3.4</span></a>)</p>
<div id="tbl-sesgo" class="anchored">
<table class="table">
<caption>Tabla&nbsp;3.4: Métricas de sesgo.</caption>
<colgroup>
<col style="width: 12%">
<col style="width: 23%">
<col style="width: 63%">
</colgroup>
<thead><tr class="header">
<th></th>
<th>Métrica</th>
<th>Fórmula</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Sin escala</td>
<td>Mean Error</td>
<td><span class="math inline">\(ME=\frac{1}{n}\sum_{l=1}^{n}\hat{e}_{T+l|T}\)</span></td>
</tr>
<tr class="even">
<td>Porcentual</td>
<td>Mean Percentage Error</td>
<td><span class="math inline">\(MPE=\frac{100}{n}\sum_{l=1}^{n}\frac{\hat{e}_{T+l|t}}{y_t}\)</span></td>
</tr>
</tbody>
</table>
</div>
<p>Las métricas de sesgo nos indican el signo del error pero no el tamaño del mismo, el cuál se define como la precisión del error. Dicho de otra forma, si utilizamos el ME, los errores positivos se compensan con los negativos y no nos da una indicación de cómo de grandes son los errores. Para completar las métricas de sesgo hay que incluir otra métricas que nos indiquen la <strong>precisión</strong> del error, es decir, su tamaño. Estas métricas transformarán los errores para evitar el signo de forma que los errores siempre sumen. Las formas más comunes para evitar el signo de los errores es usar valores absolutos o elevar los errores al cuadrado. De esta forma, se obtiene el <em>Mean Absolute Error</em> (MAE), el <em>Mean Squared Error</em> (MSE) y el <em>Root Mean Squared Error</em> (RMSE=<span class="math inline">\(\sqrt{MSE}\)</span>). En la <a href="#tbl-precision">Tabla&nbsp;<span>3.5</span></a> se muestra un resumen de las métricas de precisión. Hay que señalar que tanto el MAE como el RMSE tienen las mismas unidades que la variable de estudio <span class="math inline">\(y_t\)</span> lo que facilita su interpretación.</p>
<p>Las métricas definidas hasta ahora son útiles cuando se está analizando una serie temporal. En caso de que se necesite calcular el error de predicción sobre un conjunto de series temporales se suelen utilizar otras métricas que eliminen las unidades de cada serie temporal y así se puedan agregar los resultados. Entre estas métricas, nos encontramos los <strong>errores porcentuales</strong>, los <strong>errores escalados</strong> y los <strong>errores relativos</strong>.</p>
<p>El error porcentual (PE) se calcula como:</p>
<p><span class="math display">\[PE=\frac{\hat{e}_{T+l|T}}{y_{T+l}}\cdot 100\]</span> Por tanto, una médida de sesgo porcentual sería el <strong>Mean Percentage Error</strong> (MPE), ver <a href="#tbl-sesgo">Tabla&nbsp;<span>3.4</span></a> y una medida de tamaño sería el <em>Mean Absolute Percentage Error</em> (MAPE), ver <a href="#tbl-precision">Tabla&nbsp;<span>3.5</span></a>. A pesar de que la métrica MAPE es muy intuitiva, su uso cada vez es menor dado la asimetría que presenta, es decir, penaliza de forma diferente, de ahí su asimetría, los errores positivos y negativos. Para corregir dicha asimetría se ha propuesto el <strong>Symmetric MAPE</strong> (sMAPE), donde los denominadores son la media de valores absolutos de valores reales y predicciones.</p>
<p>Un problema que presentan las métricas porcentuales es su utilización cuando la serie temporal presenta ceros entre sus valores. Por ejemplo, las ventas de una pieza de repuesto donde en algunos periodos temporales las ventas son cero. Para solucionar la problemática de las métricas porcentuales, se han propuesto los <strong>errores escalados</strong> como el <strong>Mean Absolute Scaled Error</strong> (MASE), donde el denominador que normaliza los errores está compuesto por el error absoluto medio de las predicciones <em>Naïve</em> un paso hacia delante. De esta forma se compara la precisión de las predicciones <em>fuera</em> de la muestra con la precisión de un modelo sencillo <em>dentro</em> de la muestra. La versión cuadrática del MASE es el <strong>Root Mean Squared Scaled Error</strong> (RMSSE)</p>
<p>En la <a href="#tbl-sesgo">Tabla&nbsp;<span>3.4</span></a> y <a href="#tbl-precision">Tabla&nbsp;<span>3.5</span></a> se promedian siempre funciones del error de predicción con un horizonte de <span class="math inline">\(n\)</span> periodos hacia adelante desde el origen de predicción, que será por lo general el final de la muestra, la observación <span class="math inline">\(T\)</span>-ésima.</p>
<div id="tbl-precision" class="anchored">
<table class="table">
<caption>Tabla&nbsp;3.5: Métricas de precisión.</caption>
<colgroup>
<col style="width: 12%">
<col style="width: 23%">
<col style="width: 64%">
</colgroup>
<thead><tr class="header">
<th></th>
<th>Métrica</th>
<th style="text-align: center;">Fórmula</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><strong>Sin escala</strong></td>
<td>Mean Absolute Error</td>
<td style="text-align: center;"><span class="math inline">\(MAE=\frac{1}{n}\sum_{l=1}^{n}|\hat{e}_{T+l|T}|\)</span></td>
</tr>
<tr class="even">
<td></td>
<td>Root Mean Squared Error</td>
<td style="text-align: center;"><span class="math inline">\(RMSE=\sqrt{\frac{1}{n}\sum_{l=1}^{n}\hat{e}^2_{T+l|T}}\)</span></td>
</tr>
<tr class="odd">
<td><strong>Porcentual</strong></td>
<td>Mean Absolute Percentage Error</td>
<td style="text-align: center;"><span class="math inline">\(MAPE=\frac{100}{n}\sum_{l=1}^{n}|\frac{\hat{e}_{T+l|T}}{y_t}|\)</span></td>
</tr>
<tr class="even">
<td></td>
<td>Symmetric MAPE</td>
<td style="text-align: center;"><span class="math inline">\(sMAPE=\frac{100}{n}\sum_{l=1}^{n}|\frac{\hat{e}_{T+l|T}}{(|\hat{y}_{T+l|T}|+|y_t|)/2}|\)</span></td>
</tr>
<tr class="odd">
<td></td>
<td>Root Mean Squared Percentage Error</td>
<td style="text-align: center;"><span class="math inline">\(RMSPE=\sqrt{\frac{100}{n}\sum_{l=1}^{n}\frac{\hat{e}^2_{T+l|T}}{y_t^2}}\)</span></td>
</tr>
<tr class="even">
<td><strong>Escalada</strong></td>
<td>Mean Absolute Scaled Error</td>
<td style="text-align: center;"><span class="math inline">\(MASE=\sqrt{\frac{\frac{1}{n}\sum_{l=1}^{n}|\hat{e}_{T+l|T}|}{\frac{1}{T-1}\sum_{t=1}^T |y_t-y_{t-1}|}}\)</span></td>
</tr>
<tr class="odd">
<td></td>
<td>Root Mean Squared Scaled Error</td>
<td style="text-align: center;"><span class="math inline">\(RMSSE=\sqrt{\frac{\frac{1}{n}\sum_{l=1}^{n}\hat{e}^2_{T+l|T}}{\frac{1}{T-1}\sum_{t=1}^T (y_t-y_{t-1})^2}}\)</span></td>
</tr>
<tr class="even">
<td><strong>Relativos</strong></td>
<td>Relative MAE</td>
<td style="text-align: center;"><span class="math inline">\(RelMAE=\frac{MAE}{MAE_b}\)</span></td>
</tr>
</tbody>
</table>
</div>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-7-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-7-1" role="tab" aria-controls="tabset-7-1" aria-selected="true">Resuelve</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-7-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-7-2" role="tab" aria-controls="tabset-7-2" aria-selected="false">Solución</a></li>
</ul>
<div class="tab-content">
<div id="tabset-7-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-7-1-tab">
<p>Borra toda la memoria y carga las librerías que necesites (<code>rm</code>, <code>UComp</code>, <code>ggplot2</code>). Representa la serie pasajeros de avión en la variable <code>airpas</code> frente al tiempo con <code>autoplot</code>. La escala es muy grande, divide por 100.</p>
<p>Tomando los datos desde enero de 1995 hasta febrero de 2020, estima las predicciones a partir de marzo con los métodos sencillos (el <code>naive</code>, <code>naive estacional</code> y <code>media anual</code>) hasta el final de la muestra. Muestra las predicciones y los valores reales (<code>autoplot</code> + <code>autolayer</code>).</p>
<p>¿Qué modelo es el que tiene mayor precisión fuera de la muestra (<code>Accuracy</code>)? Estima los pasajeros que se han perdido por la pandemia (<code>colSums</code>).</p>
</div>
<div id="tabset-7-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-7-2-tab">
<div class="cell">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/rm.html">rm</a></span><span class="op">(</span>list <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/ls.html">ls</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">UComp</span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span></span>
<span><span class="va">y</span> <span class="op">=</span> <span class="va">airpas</span> <span class="op">/</span> <span class="fl">100</span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/autoplot.html">autoplot</a></span><span class="op">(</span><span class="va">y</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>title <span class="op">=</span> <span class="st">"Pasajeros"</span><span class="op">)</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="02-etsSSOE_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Tomando los datos desde enero de 1995 hasta febrero de 2020, estima las predicciones a partir de marzo con los métodos sencillos (el <code>naive</code>, <code>naive estacional</code> y <code>media anual</code>) hasta el final de la muestra. Muestra las predicciones y los valores reales (<code>autoplot</code> + <code>autolayer</code>).</p>
<div class="cell">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Horizonte de predicción</span></span>
<span><span class="va">h</span> <span class="op">=</span> <span class="fl">31</span></span>
<span><span class="co"># Seleccionamos datos entre 1995 y 2020</span></span>
<span><span class="va">x</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/window.html">window</a></span><span class="op">(</span><span class="va">y</span>, start<span class="op">=</span><span class="fl">1995</span>, end <span class="op">=</span> <span class="fl">2020</span> <span class="op">+</span> <span class="fl">1</span> <span class="op">/</span> <span class="fl">12</span><span class="op">)</span></span>
<span><span class="co"># Predicción de modelos convirtiéndolos a objetos series temporales</span></span>
<span><span class="va">naive</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/ts.html">ts</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">tail</a></span><span class="op">(</span><span class="va">x</span>, <span class="fl">1</span><span class="op">)</span>, <span class="va">h</span><span class="op">)</span>, start <span class="op">=</span> <span class="fl">2020</span> <span class="op">+</span> <span class="fl">2</span> <span class="op">/</span> <span class="fl">12</span>, frequency <span class="op">=</span> <span class="fl">12</span><span class="op">)</span></span>
<span><span class="va">snaive</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/ts.html">ts</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">tail</a></span><span class="op">(</span><span class="va">x</span>, <span class="fl">12</span><span class="op">)</span>, <span class="fl">3</span><span class="op">)</span>, <span class="va">h</span><span class="op">)</span>, start <span class="op">=</span> <span class="fl">2020</span> <span class="op">+</span> <span class="fl">2</span> <span class="op">/</span> <span class="fl">12</span>, frequency <span class="op">=</span> <span class="fl">12</span><span class="op">)</span></span>
<span><span class="va">mediaAnual</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/ts.html">ts</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">tail</a></span><span class="op">(</span><span class="va">x</span>, <span class="fl">12</span><span class="op">)</span><span class="op">)</span>, <span class="va">h</span><span class="op">)</span>, start <span class="op">=</span> <span class="fl">2020</span> <span class="op">+</span> <span class="fl">2</span> <span class="op">/</span> <span class="fl">12</span>, frequency <span class="op">=</span> <span class="fl">12</span><span class="op">)</span></span>
<span><span class="co"># Representando serie y predicciones</span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/autoplot.html">autoplot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">tail</a></span><span class="op">(</span><span class="va">y</span>, <span class="fl">80</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/autolayer.html">autolayer</a></span><span class="op">(</span><span class="va">naive</span><span class="op">)</span> <span class="op">+</span> </span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/autolayer.html">autolayer</a></span><span class="op">(</span><span class="va">snaive</span><span class="op">)</span> <span class="op">+</span> </span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/autolayer.html">autolayer</a></span><span class="op">(</span><span class="va">mediaAnual</span><span class="op">)</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="02-etsSSOE_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>¿Qué modelo es el que tiene mayor precisión fuera de la muestra (<code>Accuracy</code>)? Estima los pasajeros que se han perdido por la pandemia (<code>colSums</code>).</p>
<div class="cell">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Calculando métricas de error</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/UComp/man/Accuracy.html">Accuracy</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="va">naive</span>, <span class="va">snaive</span>, <span class="va">mediaAnual</span><span class="op">)</span>, <span class="va">y</span><span class="op">)</span></span>
<span><span class="co">##                  ME      RMSE       MAE       MPE    PRMSE      MAPE    sMAPE</span></span>
<span><span class="co">## naive       53.6947  95.61781  82.93178  857.6759 2911.154  870.0941 75.65195</span></span>
<span><span class="co">## snaive     118.6199 139.26591 118.61992 1233.4289 4085.732 1233.4289 85.71962</span></span>
<span><span class="co">## mediaAnual 112.5124 137.54520 119.63512 1206.6896 3982.979 1209.5075 87.11351</span></span>
<span><span class="co">##                MASE    RelMAE Theil's U</span></span>
<span><span class="co">## naive      14.03755 0.7228638  2.340946</span></span>
<span><span class="co">## snaive     20.07834 1.0339347  3.285460</span></span>
<span><span class="co">## mediaAnual 20.25018 1.0427836  3.202833</span></span>
<span><span class="co"># Calculando viajeros perdidos</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/colSums.html">colSums</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="va">naive</span>, <span class="va">snaive</span>, <span class="va">mediaAnual</span><span class="op">)</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">tail</a></span><span class="op">(</span><span class="va">y</span>, <span class="va">h</span><span class="op">)</span>, <span class="fl">3</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">##      naive     snaive mediaAnual </span></span>
<span><span class="co">##   1664.536   3677.217   3487.884</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Todos los modelos están sesgados al alza (no son capaces de predecir el efecto de la pandemia) si se mira el ME y MPE. El modelo más preciso es naive, seguido de naive estacional y la media anual.</p>
<p>Los pasajeros perdidos de los modelos, serían 166, 367 y 348 millones en los 31 meses evaluados según el naive, snaive y mediAnual, respectivamente.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Nota
</div>
</div>
<div class="callout-body-container callout-body">
<p>En general no hay una medida de error que pueda darnos toda la información acerca de la precisión de las predicciones, y por tanto, se recomienda el uso de varias métricas cuando se realicen predicciones. Concretamente, se recomienda, al menos, utilizar una métrica de sesgo y otra métrica de precisión.</p>
</div>
</div>
</section><section id="intervalos-de-predicción" class="level3" data-number="3.2.2"><h3 data-number="3.2.2" class="anchored" data-anchor-id="intervalos-de-predicción">
<span class="header-section-number">3.2.2</span> Intervalos de predicción</h3>
<p>Como hemos discutido anteriormente, el suavizado exponencial simple es un método de predicción y, por tanto, sólo proporciona una predicción puntual. No obstante, la predicción puntual no nos indica nada acerca de su precisión. De hecho, en muchas ocasiones las predicciones puntuales se ofrecen con numerosos decimales lo que da una idea errónea de la precisión de la predicción. Para conocer la precisión de una predicción, se suele utilizar los intervalos de predicción, los cuales consisten en un límite superior e inferior entre los cuales se espera que el valor futuro se encuentre con una probabilididad determinada. Aunque hay diferentes formas de calcular los intervalos de predicción, dado que hasta el momento estamos trabajando con <strong>métodos</strong> de predicción, se utilizarán los errores de predicción para calcular el intervalo de predicción de una forma <strong>empírica</strong>. Más adelante, cuando se describan los <strong>modelos</strong> de predicción se podrá calcular los intervalos de predicción de una forma <strong>teórica</strong>.</p>
<p>En general, un intervalo de predicción proporciona un rango dentro del cuál esperamos que se encuentre el valor real <span class="math inline">\(y_t\)</span> con una probabilidad determinada. Por ejemplo, si suponemos que la distribución de las observaciones futuras sigue una normal, un intervalo de predicción para la predicción un paso hacia adelante con una confianza del <span class="math inline">\(100(1-\alpha)\%\)</span> sería:</p>
<p><span class="math display">\[
[U_{t+1}, L_{t+1}]=[F_{t+1} \pm z_{\alpha/2} \cdot \hat{\sigma}_{t+1}]
\]</span></p>
<p>donde <span class="math inline">\(U_{t+1}\)</span> es el límite superior del intervalo de predicción, <span class="math inline">\(L_{t+1}\)</span> es el límite inferior del intervalo de predicción, <span class="math inline">\(\hat{\sigma}_{t+1}\)</span> es una estimación de la desviación típica de la distribución de las predicciones un paso hacia adelante, y <span class="math inline">\(F_{t+1}\)</span> que es la predicción puntual un paso hacia adelante proporcionada, por ejemplo, con el suavizado exponencial simple. El valor <span class="math inline">\(z_{\alpha/2}\)</span> se obtiene de la distribución normal estandard. Por ejemplo, si el nivel de confianza es del 95%, entonces <span class="math inline">\(z_{\alpha/2}=1,96\)</span>.</p>
<p>Se puede observar como el intervalo de predicción completa la información proporcionada por la predicción puntual. Concretamente, nos da una indicación de la incertidumbre asociada a la prediccion puntual, o dicho de otra forma, si el intervalo de predicción es muy amplio, la incertidumbre de la predicción puntual será grande y viceversa.</p>
<p>Normalmente, la mayor dificultad a la hora de calcular el intervalo de predicción se refiere al cálculo de <span class="math inline">\(\hat{\sigma}_{t+1}\)</span>. Una aproximación que se suéle utilizar es estimar <span class="math inline">\(\hat{\sigma}_{t+1}\)</span> con la métrica <span class="math inline">\(RMSE\)</span> obtenida del análisis de los errores de predicción, tal que <span class="math inline">\(\hat{\sigma}_{t+1}=RMSE\)</span>.</p>
</section></section><section id="suavizado-exponencial-doble-método-de-holt.-componentes-de-nivel-tendencia-y-error." class="level2" data-number="3.3"><h2 data-number="3.3" class="anchored" data-anchor-id="suavizado-exponencial-doble-método-de-holt.-componentes-de-nivel-tendencia-y-error.">
<span class="header-section-number">3.3</span> Suavizado exponencial doble (Método de Holt). Componentes de nivel, tendencia y error.</h2>
<p>Anteriormente, analizamos dos técnicas (media móvil y suavizado exponencial simple) que nos daban la predicción en caso que el patrón de los datos fuera un nivel constante con fluctuaciones aleatorias. En el caso de que los datos exhiban una tendencia positiva o negativa, el suavizado exponencial o la media móvil no proporcionarían buenas predicciones, y por tanto, el suavizado exponencial debe ser modificado para incluir tendencias en el modelo.</p>
<p>En esta sección, se analizará la versión del suavizado exponencial que incluye la componente de tendencia, dicho de otra forma, se está asumiendo que el modelo generador de datos es:</p>
<p><span class="math display">\[
    y(t)= N + T + e
\]</span></p>
<p>donde se ha incluido la componente de tendencia (<span class="math inline">\(T\)</span>) en forma aditiva. Si incluimos la componente de tendencia se obtiene la siguiente expresión también conocida como el <strong>doble suavizado exponencial</strong> o <strong>método de Holt</strong>:</p>
<p><span class="math display">\[
\begin{eqnarray}
L_t&amp;=&amp;\alpha(Y_t) + (1-\alpha)[L_{t-1} + b_{t-1}] \\
b_t&amp;=&amp;\beta(L_t - L_{t-1}) + (1-\beta)b_{t-1}  \\
F_{t+1} &amp;=&amp; L_t + b_t
\end{eqnarray}
\]</span></p>
<p>donde <span class="math inline">\(L_t\)</span> es la componente de nivel y <span class="math inline">\(b_t\)</span> la componente de tendencia, la cual se actualiza con la diferencia de <span class="math inline">\(L_t - L_{t-1}\)</span>. La nueva componente de tendencia, también incluye una nueva constante de suavizado <span class="math inline">\(\beta\)</span> que es un parámetro de diseño como <span class="math inline">\(\alpha\)</span>.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-8-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-8-1" role="tab" aria-controls="tabset-8-1" aria-selected="true">Resuelve</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-8-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-8-2" role="tab" aria-controls="tabset-8-2" aria-selected="false">Solución con Excel</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-8-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-8-3" role="tab" aria-controls="tabset-8-3" aria-selected="false">Solución con R</a></li>
</ul>
<div class="tab-content">
<div id="tabset-8-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-8-1-tab">
<p>Un determinado productor está utilizando la técnica de doble suavizado exponencial para predecir la demanda de una pieza del equipamiento de control de contaminación, ver datos en las dos primeras columnas de la <a href="#tbl-holt1">Tabla&nbsp;<span>3.6</span></a>. Parece que los datos contienen cierta tendencia. Las constantes de suavizado que ha definido la empresa son <span class="math inline">\(\alpha=0.2\)</span> y <span class="math inline">\(\beta=0.4\)</span>. Se supone que el nivel inicial (<span class="math inline">\(L_1\)</span>) fue 11 unidades y la tendencia en dicho periodo (<span class="math inline">\(b_1\)</span>) fue 2. Calcule las predicciones para dicha pieza mediante el método de Holt.</p>
<div id="tbl-holt1" class="anchored">
<table class="table">
<caption>Tabla&nbsp;3.6: Datos de demanda mensuales.</caption>
<thead><tr class="header">
<th style="text-align: center;"><strong>Mes</strong></th>
<th style="text-align: center;"><strong>Demanda</strong></th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">12</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">17</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">20</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">19</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: center;">24</td>
</tr>
<tr class="even">
<td style="text-align: center;">6</td>
<td style="text-align: center;">21</td>
</tr>
<tr class="odd">
<td style="text-align: center;">7</td>
<td style="text-align: center;">31</td>
</tr>
<tr class="even">
<td style="text-align: center;">8</td>
<td style="text-align: center;">28</td>
</tr>
<tr class="odd">
<td style="text-align: center;">9</td>
<td style="text-align: center;">36</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="tabset-8-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-8-2-tab">
<div id="tbl-holtsol" class="anchored">
<table class="table">
<caption>Tabla&nbsp;3.7: Datos de demanda mensuales. Componentes de la series temporal estimados por el método de Holt.</caption>
<colgroup>
<col style="width: 12%">
<col style="width: 15%">
<col style="width: 20%">
<col style="width: 25%">
<col style="width: 13%">
<col style="width: 13%">
</colgroup>
<thead><tr class="header">
<th style="text-align: center;"><strong>Mes</strong></th>
<th style="text-align: center;"><strong>Demanda</strong></th>
<th style="text-align: center;"><strong>Nivel (<span class="math inline">\(L_t\)</span>)</strong></th>
<th style="text-align: center;"><strong>Tendencia (<span class="math inline">\(b_t\)</span>)</strong></th>
<th style="text-align: center;"><strong>Holt</strong></th>
<th style="text-align: center;"><strong>SES</strong></th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">12</td>
<td style="text-align: center;">11</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">12</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">17</td>
<td style="text-align: center;">13.8</td>
<td style="text-align: center;">2.3</td>
<td style="text-align: center;">13.0</td>
<td style="text-align: center;">12.0</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">20</td>
<td style="text-align: center;">16.9</td>
<td style="text-align: center;">2.6</td>
<td style="text-align: center;">16.1</td>
<td style="text-align: center;">13.0</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">19</td>
<td style="text-align: center;">19.4</td>
<td style="text-align: center;">2.6</td>
<td style="text-align: center;">19.5</td>
<td style="text-align: center;">14.4</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: center;">24</td>
<td style="text-align: center;">22.4</td>
<td style="text-align: center;">2.7</td>
<td style="text-align: center;">22.0</td>
<td style="text-align: center;">15.3</td>
</tr>
<tr class="even">
<td style="text-align: center;">6</td>
<td style="text-align: center;">21</td>
<td style="text-align: center;">24.3</td>
<td style="text-align: center;">2.4</td>
<td style="text-align: center;">25.2</td>
<td style="text-align: center;">17.1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">7</td>
<td style="text-align: center;">31</td>
<td style="text-align: center;">27.6</td>
<td style="text-align: center;">2.8</td>
<td style="text-align: center;">26.7</td>
<td style="text-align: center;">17.8</td>
</tr>
<tr class="even">
<td style="text-align: center;">8</td>
<td style="text-align: center;">28</td>
<td style="text-align: center;">29.9</td>
<td style="text-align: center;">2.6</td>
<td style="text-align: center;">30.3</td>
<td style="text-align: center;">20.5</td>
</tr>
<tr class="odd">
<td style="text-align: center;">9</td>
<td style="text-align: center;">36</td>
<td style="text-align: center;">33.2</td>
<td style="text-align: center;">2.9</td>
<td style="text-align: center;">32.4</td>
<td style="text-align: center;">22.0</td>
</tr>
</tbody>
</table>
</div>
<p>En la tercera y cuarta columna de esa misma tabla se muestran las estimaciones de las componentes de la serie temporal <span class="math inline">\(L_t\)</span> y <span class="math inline">\(b_t\)</span> junto con las predicciones obtenidas mediante el método de Holt (quinta columna) y el suavizado exponencial simple (sexta columna), donde para este último se utilizó un <span class="math inline">\(\alpha=0.2\)</span>. En la <a href="#fig-ejemploholt2">Figura&nbsp;<span>3.6</span></a> se han dibujado la demanda junto con las predicciones. Se puede observar como las predicciones mediante el método de Holt capturan la tendencia incluida en la serie temporal, mientras que el suavizado exponencial simple (SES) no proporciona una buena predicción de la serie temporal.</p>
<div id="fig-ejemploholt2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="ejemploholtfig1.jpg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figura&nbsp;3.6: Resultados de predicción.</figcaption></figure>
</div>
</div>
<div id="tabset-8-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-8-3-tab">
<p>Como hicimos con el suavizado exponencial simple podríamos programar una función que implementara las ecuaciones del método de Holt. Sin embargo, todas esas ecuaciones se han implementado en el paquete UComp. Concretamente, en la función ETS que se detallará más adelante. Por el momento, lo que necesitamos definir es ¿cuáles son las componentes de la serie temporal? De hecho, ETS hace referencia al Error, Tendencia y eStacionalidad. Hasta ahora sólo consideraremos ruidos aditivos. Según el gráfico de las ventas, la tendencia es aditiva y tampoco hay indicios de estacionalidad. Por tanto el modelo ETS equivalente al método de Holt será ETS=“AAN”. De la misma forma, el modelo ETS equivalente al suavizado exponencial simple será ETS=“ANN”. Hay que señalar que la optimización de los parámetros y la inicialización la realiza automáticamente la función ETS.</p>
<div class="cell">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/rm.html">rm</a></span><span class="op">(</span>list <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/ls.html">ls</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">UComp</span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Ventas</span></span>
<span><span class="va">yts</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/stats/ts.html">ts</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">12</span>,<span class="fl">17</span>,<span class="fl">20</span>,<span class="fl">19</span>,<span class="fl">24</span>,<span class="fl">21</span>,<span class="fl">31</span>,<span class="fl">28</span>,<span class="fl">36</span><span class="op">)</span>,start<span class="op">=</span><span class="fl">1</span>,end<span class="op">=</span><span class="fl">9</span><span class="op">)</span></span>
<span><span class="co"># Selecionando muestra</span></span>
<span><span class="va">x</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/window.html">window</a></span><span class="op">(</span><span class="va">yts</span>, start<span class="op">=</span><span class="fl">1</span>, end <span class="op">=</span> <span class="fl">8</span><span class="op">)</span></span>
<span><span class="co"># Horizonte de predicción</span></span>
<span><span class="va">h</span> <span class="op">=</span> <span class="fl">1</span></span>
<span><span class="co"># Estimando y prediciendo con Doble Suavizado Exponencial</span></span>
<span><span class="va">mholt</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/UComp/man/ETS.html">ETS</a></span><span class="op">(</span><span class="va">x</span>, model<span class="op">=</span><span class="st">"AAN"</span>, h <span class="op">=</span> <span class="va">h</span><span class="op">)</span></span>
<span><span class="va">predholt</span><span class="op">&lt;-</span><span class="va">mholt</span><span class="op">$</span><span class="va">yFor</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">predholt</span><span class="op">)</span></span>
<span><span class="co">## Time Series:</span></span>
<span><span class="co">## Start = 9 </span></span>
<span><span class="co">## End = 9 </span></span>
<span><span class="co">## Frequency = 1 </span></span>
<span><span class="co">##      Series 1</span></span>
<span><span class="co">## [1,] 31.67857</span></span>
<span><span class="co"># Estimando y prediciendo con Suavizado Exponencial Simple</span></span>
<span><span class="va">mses</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/UComp/man/ETS.html">ETS</a></span><span class="op">(</span><span class="va">x</span>, model<span class="op">=</span><span class="st">"ANN"</span>, h<span class="op">=</span><span class="va">h</span><span class="op">)</span></span>
<span><span class="va">predSES</span><span class="op">&lt;-</span><span class="va">mses</span><span class="op">$</span><span class="va">yFor</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">predSES</span><span class="op">)</span></span>
<span><span class="co">## Time Series:</span></span>
<span><span class="co">## Start = 9 </span></span>
<span><span class="co">## End = 9 </span></span>
<span><span class="co">## Frequency = 1 </span></span>
<span><span class="co">##      Series 1</span></span>
<span><span class="co">## [1,] 28.14612</span></span>
<span><span class="co"># Podemos dibujar el ajuste </span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/autoplot.html">autoplot</a></span><span class="op">(</span><span class="va">yts</span><span class="op">)</span><span class="op">+</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/autolayer.html">autolayer</a></span><span class="op">(</span><span class="va">mholt</span><span class="op">$</span><span class="va">comp</span><span class="op">[</span>,<span class="fl">2</span><span class="op">]</span><span class="op">)</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="02-etsSSOE_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
</div>
</div>
<p>Al igual que ocurrió con el suavizado exponencial simple, tenemos que decidir como inicializar el algoritmo, o lo que es lo mismo, estimar los valores iniciales de nivel (<span class="math inline">\(L_1\)</span>) y pendiente (<span class="math inline">\(b_1\)</span>). Una posibilidad es la siguiente:</p>
<p><span class="math display">\[
L_1=\frac{(Y_1+Y_2+\ldots+Y_n)}{s}
\]</span></p>
<p><span class="math display">\[
b_1=\frac{1}{n-1}\left[\frac{(Y_{2}-Y_1)}{1}+\frac{(Y_{3}-Y_2)}{1}+\ldots+\frac{(Y_{n}-Y_{n-1})}{1}\right]
\]</span></p>
<p>donde <span class="math inline">\(n\)</span> es el número de observaciones utilizadas para la inicialización. Por ejemplo, con las tres o cuatro primeras observaciones puede ser suficiente.</p>
</section><section id="triple-suavizado-exponencial-holt-winters.-componentes-de-nivel-tendencia-y-estacionalidad" class="level2" data-number="3.4"><h2 data-number="3.4" class="anchored" data-anchor-id="triple-suavizado-exponencial-holt-winters.-componentes-de-nivel-tendencia-y-estacionalidad">
<span class="header-section-number">3.4</span> Triple suavizado exponencial (Holt-Winters). Componentes de nivel, tendencia y estacionalidad</h2>
<p>Los métodos anteriores funcionan bien cuando no existe estacionalidad en los datos. En el caso de que también exista estacionalidad y sea multiplicativa, nuestro modelo sería:</p>
<p><span id="eq-HW"><span class="math display">\[
\begin{eqnarray}
L_t&amp;=&amp;\alpha(\frac{Y_t}{S_{t-s}}) + (1-\alpha)[L_{t-1} + b_{t-1}] \label{nivelHW} \\
b_t&amp;=&amp;\beta(L_t - L_{t-1}) + (1-\beta)b_{t-1}  \label{trendBH}\\
S_t&amp;=&amp;\gamma\frac{Y_t}{L_t} + (1-\gamma)S_{t-s} \\
F_{t+1} &amp;=&amp; (L_t + b_t )S_{t-s+1} \label{forecastHW}
\end{eqnarray}
\tag{3.6}\]</span></span></p>
<p>donde <span class="math inline">\(s\)</span> es la duración de la estacionalidad. A este modelo se le conoce como modelo de Holt-Winters (HW). El algoritmo fue desarrollado por CC. Holt en 1957 y su estudiante Peter Winters en 1960. La cuestión sobre si la estacionalidad es aditiva o multiplicativa, volveremos sobre este punto más tarde.</p>
<p>Para realizar las predicciones el modelo necesita estimar las componentes de nivel, tendencia y estacionalidad. La primera línea de la <a href="#eq-HW">Ecuación&nbsp;<span>3.7</span></a> representa el nivel (<span class="math inline">\(L_t\)</span>) subyacente de la serie temporal. Este es el nivel después de haber desestacionalizado la serie temporal y filtrado el efecto del error aleatorio o ruido. La siguiente línea representa el cambio de nivel de la serie es decir la tendencia (<span class="math inline">\(b_t\)</span>). El último componente hace referencia a la estacionalidad (<span class="math inline">\(S_t\)</span>) y se conoce como el <strong>índice estacional</strong>. Por ejemplo, si el índice estacional vale 1.2 significa que se espera que las serie temporal en ese periodo de tiempo sea un 20% superior al nivel promedio. Es importante señalar que, en el método de Holt-Winters, tenemos que indicar cuál es el valor de la estacionalidad <span class="math inline">\(s\)</span> que no hay que confundir con la componente estacional <span class="math inline">\(S_t\)</span>. Por lo general, en series temporales económicas, dicho valor de estacionalidad <span class="math inline">\(s\)</span> suele ser anual. Por tanto, si la serie es mensual (<span class="math inline">\(s=12\)</span>), y si la serie es trimestral (<span class="math inline">\(s=4\)</span>).</p>
<p>Por otro lado los parámetros <span class="math inline">\(\alpha\)</span>, <span class="math inline">\(\beta\)</span> y <span class="math inline">\(\gamma\)</span> son constantes y se denominan <em>constantes de suavizado</em>. Para cada componente (ecuación) hay una constante de suavizado que puede variar entre un rango de 0 a 1. Cuanto mayor sea la constante, mayor será el peso aplicado a la última observación y menor el peso aplicado a la última estimación. En otras palabras, el método se adaptará más rápido a cambios en el nivel, tendencia o estacionalidad. Sin embargo, también será más sensible al ruido. Finalmente, la última ecuación del algoritmo en <a href="#eq-HW">Ecuación&nbsp;<span>3.7</span></a> muestra combinación de los componentes para producir la predicción un paso hacia adelante <span class="math inline">\(F_{t+1}\)</span>. Dicha última ecuación muestra como la combinación de la componente de tendencia y nivel es aditiva, mientras que la componente estacional se incluye de forma multiplicativa.</p>
<p>Al igual que el resto de métodos de suavizado exponencial se pueden utilizar técnicas heurísticas para inicializar el algoritmo. En este caso, se necesitarán <span class="math inline">\(2s\)</span> observaciones para inicializar el método de Holt-Winters, tal que, para la inicialización de la componente de nivel <span class="math inline">\(L_t\)</span>:</p>
<p><span class="math display">\[
L_s=\frac{\sum_{i=1}^s Y_i}{s}
\]</span></p>
<p>Para la inialización de la componente de tendencia <span class="math inline">\(b_t\)</span>:</p>
<p><span class="math display">\[
b_s=\frac{1}{s}[\frac{Y_{s+1}-Y_1}{s}+\frac{Y_{s+2}-Y_2}{s}+\frac{Y_{s+3}-Y_3}{s}+\ldots + \frac{Y_{s+s}-Y_s}{s}]
\]</span> Y, finalmente, para los índices estacionales:</p>
<p><span class="math display">\[
S_1=\frac{Y_1}{L_s}, S_2=\frac{Y_2}{L_s},\ldots,S_s\frac{Y_s}{L_s}
\]</span></p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-9-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-9-1" role="tab" aria-controls="tabset-9-1" aria-selected="true">Resuelve</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-9-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-9-2" role="tab" aria-controls="tabset-9-2" aria-selected="false">Solución con Excel</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-9-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-9-3" role="tab" aria-controls="tabset-9-3" aria-selected="false">Solución con R</a></li>
</ul>
<div class="tab-content">
<div id="tabset-9-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-9-1-tab">
<p>En la <a href="#tbl-ejestaci">Tabla&nbsp;<span>3.8</span></a> se muestran las ventas trimestrales de un determinado producto. Se pide dibujar las ventas frente al tiempo e identificar los componentes. En caso de que hay indicios de una componente estacional utilice el método de HW para realizar la predicción del trimestre 25. Finalmente, dibuje las predicciones frente a los datos reales para los periodos anteriores. Compara las predicciones con el método SES y de Holt.</p>
<div id="tbl-ejestaci" class="anchored">
<table class="table">
<caption>Tabla&nbsp;3.8: Ejemplo con datos estacionales.</caption>
<thead><tr class="header">
<th style="text-align: center;">Trimestre</th>
<th style="text-align: center;">Ventas</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">362</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">385</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">432</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">341</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: center;">382</td>
</tr>
<tr class="even">
<td style="text-align: center;">6</td>
<td style="text-align: center;">409</td>
</tr>
<tr class="odd">
<td style="text-align: center;">7</td>
<td style="text-align: center;">498</td>
</tr>
<tr class="even">
<td style="text-align: center;">8</td>
<td style="text-align: center;">387</td>
</tr>
<tr class="odd">
<td style="text-align: center;">9</td>
<td style="text-align: center;">473</td>
</tr>
<tr class="even">
<td style="text-align: center;">10</td>
<td style="text-align: center;">513</td>
</tr>
<tr class="odd">
<td style="text-align: center;">11</td>
<td style="text-align: center;">582</td>
</tr>
<tr class="even">
<td style="text-align: center;">12</td>
<td style="text-align: center;">474</td>
</tr>
<tr class="odd">
<td style="text-align: center;">13</td>
<td style="text-align: center;">544</td>
</tr>
<tr class="even">
<td style="text-align: center;">14</td>
<td style="text-align: center;">582</td>
</tr>
<tr class="odd">
<td style="text-align: center;">15</td>
<td style="text-align: center;">681</td>
</tr>
<tr class="even">
<td style="text-align: center;">16</td>
<td style="text-align: center;">557</td>
</tr>
<tr class="odd">
<td style="text-align: center;">17</td>
<td style="text-align: center;">628</td>
</tr>
<tr class="even">
<td style="text-align: center;">18</td>
<td style="text-align: center;">707</td>
</tr>
<tr class="odd">
<td style="text-align: center;">19</td>
<td style="text-align: center;">773</td>
</tr>
<tr class="even">
<td style="text-align: center;">20</td>
<td style="text-align: center;">592</td>
</tr>
<tr class="odd">
<td style="text-align: center;">21</td>
<td style="text-align: center;">627</td>
</tr>
<tr class="even">
<td style="text-align: center;">22</td>
<td style="text-align: center;">725</td>
</tr>
<tr class="odd">
<td style="text-align: center;">23</td>
<td style="text-align: center;">854</td>
</tr>
<tr class="even">
<td style="text-align: center;">24</td>
<td style="text-align: center;">661</td>
</tr>
<tr class="odd">
<td style="text-align: center;">25</td>
<td style="text-align: center;">?</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="tabset-9-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-9-2-tab">
<p>En la <a href="#fig-winter1">Figura&nbsp;<span>3.7</span></a> se puede apreciar la presencia de las componentes de nivel, tendencia y estacionalidad. Por tanto, un método que puede funcionar bien a la hora de realizar predicciones es el método HW.</p>
<div id="fig-winter1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="winter1.jpg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figura&nbsp;3.7: Ventas de un producto con caracter estacional.</figcaption></figure>
</div>
<p>Para poder utilizar <a href="#eq-HW">Ecuación&nbsp;<span>3.7</span></a> se necesita proporcionar el valor de la estacionalidad (<span class="math inline">\(s\)</span>) de la serie temporal. En el caso del ejemplo de la <a href="#fig-winter1">Figura&nbsp;<span>3.7</span></a>, el valor de <span class="math inline">\(s=4\)</span>, es decir, los valores siguen un patrón cíclico cada 4 observaciones y como los datos son trimestrales, tiene una estacionalidad anual.</p>
<p>En la <a href="#fig-winter2">Figura&nbsp;<span>3.8</span></a> se muestra las diferentes estimaciones correspondientes a cada componente, donde los valores de los parámetros optimizados han sido <span class="math inline">\(\alpha=0,82\)</span>, <span class="math inline">\(\beta=0,055\)</span> y <span class="math inline">\(\gamma=0\)</span>. En la columna Holt-Winter se muestra la predicción resultante.</p>
<div id="fig-winter2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="winter2.jpg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figura&nbsp;3.8: Estimación de las componentes de nivel, tendencia y estacionalidad, junto con la predicción en la columna Holt-Winters.</figcaption></figure>
</div>
<p>La <a href="#fig-winter3">Figura&nbsp;<span>3.9</span></a> representa la demanda real junto con las diferentes predicciones realizadas por los métodos de: i) suavizado exponencial simple, ii) doble suavizado exponencial (método de Holt) y iii) el método HW. Se puede comprobar visualmente que es el método de HW el que se aproxima mejor a la demanda real.</p>
<div id="fig-winter3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="winter3.jpg" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figura&nbsp;3.9: Predicciones realizadas mediante los diferentes tipos de suavizado exponencial.</figcaption></figure>
</div>
</div>
<div id="tabset-9-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-9-3-tab">
<p>Se pide dibujar las ventas frente al tiempo e identificar los componentes. En caso de que hay indicios de una componente estacional utilice el método de HW para realizar la predicción del trimestre 25. Finalmente, dibuje las predicciones frente a los datos reales para los periodos anteriores. Compara las predicciones con el método SES y de Holt.</p>
<div class="cell">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/rm.html">rm</a></span><span class="op">(</span>list <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/ls.html">ls</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">UComp</span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Ventas</span></span>
<span><span class="va">ventas</span><span class="op">&lt;-</span><span class="fu"><a href="https://rdrr.io/r/stats/ts.html">ts</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">362</span>,<span class="fl">385</span>,<span class="fl">432</span>,<span class="fl">341</span>,<span class="fl">382</span>,<span class="fl">409</span>,<span class="fl">498</span>,<span class="fl">387</span>,<span class="fl">473</span>,<span class="fl">513</span>,<span class="fl">582</span>,<span class="fl">474</span>,<span class="fl">544</span>,<span class="fl">582</span>,<span class="fl">681</span>,<span class="fl">557</span>,<span class="fl">628</span>,<span class="fl">707</span>,<span class="fl">773</span>,<span class="fl">592</span>,<span class="fl">627</span>,<span class="fl">725</span>,<span class="fl">854</span>,<span class="fl">661</span><span class="op">)</span>,start<span class="op">=</span><span class="fl">1</span>,frequency<span class="op">=</span><span class="fl">4</span><span class="op">)</span></span>
<span><span class="co"># Dibujo los datos</span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/autoplot.html">autoplot</a></span><span class="op">(</span><span class="va">ventas</span><span class="op">)</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="02-etsSSOE_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Selecionando muestra</span></span>
<span><span class="va">x</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/window.html">window</a></span><span class="op">(</span><span class="va">ventas</span>, start<span class="op">=</span><span class="fl">1</span>, end <span class="op">=</span> <span class="fl">23</span><span class="op">)</span></span>
<span><span class="co"># Horizonte de predicción</span></span>
<span><span class="va">h</span> <span class="op">=</span> <span class="fl">1</span></span>
<span><span class="co"># Estimando y prediciendo con Triple Suavizado Exponencial</span></span>
<span><span class="va">mhw</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/UComp/man/ETS.html">ETS</a></span><span class="op">(</span><span class="va">x</span>, model<span class="op">=</span><span class="st">"MAM"</span>, h <span class="op">=</span> <span class="va">h</span><span class="op">)</span></span>
<span><span class="va">predhw</span><span class="op">&lt;-</span><span class="va">mhw</span><span class="op">$</span><span class="va">yFor</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">predhw</span><span class="op">)</span></span>
<span><span class="co">##       Qtr1</span></span>
<span><span class="co">## 7 738.9385</span></span>
<span><span class="co"># Estimando y prediciendo con Doble Suavizado Exponencial</span></span>
<span><span class="va">mholt</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/UComp/man/ETS.html">ETS</a></span><span class="op">(</span><span class="va">x</span>, model<span class="op">=</span><span class="st">"AAN"</span>, h <span class="op">=</span> <span class="va">h</span><span class="op">)</span></span>
<span><span class="va">predholt</span><span class="op">&lt;-</span><span class="va">mholt</span><span class="op">$</span><span class="va">yFor</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">predholt</span><span class="op">)</span></span>
<span><span class="co">##       Qtr1</span></span>
<span><span class="co">## 7 771.5507</span></span>
<span><span class="co"># Estimando y prediciendo con Suavizado Exponencial Simple</span></span>
<span><span class="va">mses</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/UComp/man/ETS.html">ETS</a></span><span class="op">(</span><span class="va">x</span>, model<span class="op">=</span><span class="st">"ANN"</span>, h<span class="op">=</span><span class="va">h</span><span class="op">)</span></span>
<span><span class="va">predSES</span><span class="op">&lt;-</span><span class="va">mses</span><span class="op">$</span><span class="va">yFor</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="va">predSES</span><span class="op">)</span></span>
<span><span class="co">##      Qtr1</span></span>
<span><span class="co">## 7 714.505</span></span>
<span><span class="co"># Podemos dibujar el ajuste </span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/autoplot.html">autoplot</a></span><span class="op">(</span><span class="va">ventas</span><span class="op">)</span><span class="op">+</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/autolayer.html">autolayer</a></span><span class="op">(</span><span class="va">mholt</span><span class="op">$</span><span class="va">comp</span><span class="op">[</span>,<span class="fl">2</span><span class="op">]</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/autolayer.html">autolayer</a></span><span class="op">(</span><span class="va">mhw</span><span class="op">$</span><span class="va">comp</span><span class="op">[</span>,<span class="fl">2</span><span class="op">]</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/autolayer.html">autolayer</a></span><span class="op">(</span><span class="va">mses</span><span class="op">$</span><span class="va">comp</span><span class="op">[</span>,<span class="fl">2</span><span class="op">]</span><span class="op">)</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="02-etsSSOE_files/figure-html/unnamed-chunk-11-2.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
</div>
</div>
</section><section id="clasificación-de-pegels" class="level2" data-number="3.5"><h2 data-number="3.5" class="anchored" data-anchor-id="clasificación-de-pegels">
<span class="header-section-number">3.5</span> Clasificación de Pegels</h2>
<p>Hasta ahora se han analizado las diferentes versiones de suavizado exponencial en función de los componentes que posea la serie temporal (nivel, tendencia, estacionalidad y error). Los métodos analizados son los más comunes, no obstante pueden existir más combinaciones , por ejemplo ¿cómo podríamos realizar la predicción de una serie temporal que posea nivel y estacionalidad combinados de una manera aditiva?</p>
<p>Para solucionar esta pregunta Pegels (1969) propuso la <a href="#tbl-Pegels">Tabla&nbsp;<span>3.9</span></a>. De esta forma, una vez que se hayan identificado los componentes de la serie temporal (tendencia o estacionalidad) y la forma en que se combinan (multiplicativa o aditiva) se selecciona el cuadrante de la tabla. De dicha tabla se obtienen los valores de <span class="math inline">\(P_t\)</span>, <span class="math inline">\(Q_t\)</span>, <span class="math inline">\(R_t\)</span> y <span class="math inline">\(T_t\)</span>, y se sustituyen en las siguientes ecuaciones:</p>
<p><span class="math display">\[
\begin{eqnarray}
    L_t&amp;=&amp;\alpha P_t + (1-\alpha)Q_t \\
    b_t&amp;=&amp;\beta R_t + (1-\beta)b_{t-1} \\
    S_t&amp;=&amp;\gamma T_t + (1-\gamma) S_{t-s}
\end{eqnarray}
\]</span></p>
<p>Finalmente la predicción se obtiene mediante la ecuación <span class="math inline">\(F_{t+m}\)</span> que se obtiene de la <a href="#tbl-Pegels">Tabla&nbsp;<span>3.9</span></a>. Es importante señalar que hasta ahora hemos supuesto que las predicciones las realizamos un paso hacia delante, es decir, se calcula <span class="math inline">\(F_{t+1}\)</span>. No obstante, puede ser necesario predicciones con un horizonte temporal mayor, digamos <span class="math inline">\(m\)</span> pasos adelante. Por ello, la constante <span class="math inline">\(m\)</span> nos indica el número de pasos adelante que queremos realizar la predicción.</p>
<div id="tbl-Pegels" class="anchored">
<table class="table">
<caption>Tabla&nbsp;3.9: Clasificación de Pegels.</caption>
<colgroup>
<col style="width: 19%">
<col style="width: 22%">
<col style="width: 28%">
<col style="width: 29%">
</colgroup>
<thead><tr class="header">
<th><strong>Tendencia</strong></th>
<th></th>
<th><strong>Estacionalidad</strong></th>
<th></th>
</tr></thead>
<tbody>
<tr class="odd">
<td></td>
<td>(Ninguna)</td>
<td>(Aditiva)</td>
<td>(Multiplicativa)</td>
</tr>
<tr class="even">
<td></td>
<td><span class="math inline">\(P_t=Y_t\)</span></td>
<td><span class="math inline">\(P_t=Y_t-S_{t-s}\)</span></td>
<td><span class="math inline">\(P_t=Y_t/S_{t-s}\)</span></td>
</tr>
<tr class="odd">
<td>(Ninguna)</td>
<td><span class="math inline">\(Q_t=L_{t-1}\)</span></td>
<td><span class="math inline">\(Q_t=L_{t-1}\)</span></td>
<td><span class="math inline">\(Q_t=L_{t-1}\)</span></td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td><span class="math inline">\(T_t=Y_t-L_t\)</span></td>
<td><span class="math inline">\(T_t=Y_t/L_t\)</span></td>
</tr>
<tr class="odd">
<td></td>
<td><span class="math inline">\(F_{t+m}=L_t\)</span></td>
<td><span class="math inline">\(F_{t+m}=L_t+S_{t+m-s}\)</span></td>
<td><span class="math inline">\(F_{t+m}=L_tS_{t+m-s}\)</span></td>
</tr>
<tr class="even">
<td>————-</td>
<td>———–</td>
<td>————</td>
<td>————–</td>
</tr>
<tr class="odd">
<td></td>
<td><span class="math inline">\(P_t=Y_t\)</span></td>
<td><span class="math inline">\(P_t=Y_t-S_{t-s}\)</span></td>
<td><span class="math inline">\(P_t=Y_t/S_{t-s}\)</span></td>
</tr>
<tr class="even">
<td></td>
<td><span class="math inline">\(Q_t=L_{t-1}+b_{t-1}\)</span></td>
<td><span class="math inline">\(Q_t=L_{t-1}+b_{t-1}\)</span></td>
<td><span class="math inline">\(Q_t=L_{t-1}+b_{t-1}\)</span></td>
</tr>
<tr class="odd">
<td>(Aditiva)</td>
<td><span class="math inline">\(R_t=L_t-L_{t-1}\)</span></td>
<td><span class="math inline">\(R_t=L_t-L_{t-1}\)</span></td>
<td><span class="math inline">\(R_t=L_t-L_{t-1}\)</span></td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td><span class="math inline">\(T_t=Y_t-L_t\)</span></td>
<td><span class="math inline">\(T_t=Y_t/L_t\)</span></td>
</tr>
<tr class="odd">
<td></td>
<td><span class="math inline">\(F_{t+m}=L_t+mb_t\)</span></td>
<td><span class="math inline">\(F_{t+m}=L_t+mb_t+S_{t+m-s}\)</span></td>
<td><span class="math inline">\(F_{t+m}=(L_t+mb_t)S_{t+m-s}\)</span></td>
</tr>
<tr class="even">
<td>——————–</td>
<td>———————–</td>
<td>——————————</td>
<td>——————————-</td>
</tr>
<tr class="odd">
<td></td>
<td><span class="math inline">\(P_t=Y_t\)</span></td>
<td><span class="math inline">\(P_t=Y_t-S_{t-s}\)</span></td>
<td><span class="math inline">\(P_t=Y_t/S_{t-s}\)</span></td>
</tr>
<tr class="even">
<td></td>
<td><span class="math inline">\(Q_t=L_{t-1}b_{t-1}\)</span></td>
<td><span class="math inline">\(Q_t=L_{t-1}b_{t-1}\)</span></td>
<td><span class="math inline">\(Q_t=L_{t-1}b_{t-1}\)</span></td>
</tr>
<tr class="odd">
<td>(Multiplicativa)</td>
<td><span class="math inline">\(R_t=L_t/L_{t-1}\)</span></td>
<td><span class="math inline">\(R_t=L_t/L_{t-1}\)</span></td>
<td><span class="math inline">\(R_t=L_t/L_{t-1}\)</span></td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td><span class="math inline">\(T_t=Y_t-L_t\)</span></td>
<td><span class="math inline">\(T_t=Y_t/L_t\)</span></td>
</tr>
<tr class="odd">
<td></td>
<td><span class="math inline">\(F_{t+m}=L_tb_t^m\)</span></td>
<td><span class="math inline">\(F_{t+m}=L_tb_t^m+S_{t+m-s}\)</span></td>
<td><span class="math inline">\(F_{t+m}=L_tb_t^mS_{t+m-s}\)</span></td>
</tr>
</tbody>
</table>
</div>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist">
<li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-10-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-10-1" role="tab" aria-controls="tabset-10-1" aria-selected="true">Resuelve</a></li>
<li class="nav-item" role="presentation"><a class="nav-link" id="tabset-10-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-10-2" role="tab" aria-controls="tabset-10-2" aria-selected="false">Solución</a></li>
</ul>
<div class="tab-content">
<div id="tabset-10-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-10-1-tab">
<p>Utilizando la clasificación de Pegels, calcular las ecuaciones de suavizado exponencial necesarias para realizar la predicción de una serie temporal cuyas componentes son nivel y tendencia (de forma aditiva) y estacionalidad de forma multiplicativa, es decir, comprobar que dichas ecuaciones coinciden con las obtenidas para el método HW.</p>
</div>
<div id="tabset-10-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-10-2-tab">
<p>Utilizando la clasificación de Pegels, calcular las ecuaciones de suavizado exponencial necesarias para realizar la predicción de una serie temporal cuyas componentes son nivel y tendencia (de forma aditiva) y estacionalidad de forma multiplicativa, es decir, comprobar que dichas ecuaciones coinciden con las obtenidas para el método HW.</p>
<p>Se puede apreciar que si las componentes son nivel y tendencia de forma aditiva y estacionalidad de forma multiplicativa coincide con el método de Holt-Winters y las ecuaciones son:</p>
<p><span class="math display">\[
\begin{eqnarray}
    L_t&amp;=&amp;\alpha P_t + (1-\alpha)Q_t \\
    b_t&amp;=&amp;\beta R_t + (1-\beta)b_{t-1} \\
    S_t&amp;=&amp;\gamma T_t + (1-\gamma) S_{t-s}
\end{eqnarray}
\]</span></p>
<p>donde <span class="math inline">\(P_t\)</span>, <span class="math inline">\(Q_t\)</span>, <span class="math inline">\(R_t\)</span>, <span class="math inline">\(T_t\)</span> se obtienen de la <a href="#tbl-Pegels">Tabla&nbsp;<span>3.9</span></a> y son:</p>
<p><span class="math display">\[
\begin{eqnarray}
P_t&amp;=&amp;Y_t/S_{t-s} \\
Q_t&amp;=&amp;L_{t-1}+b_{t-1} \\
R_t&amp;=&amp;L_t-L_{t-1} \\
T_t&amp;=&amp;Y_t/L_t
\end{eqnarray}
\]</span> Finalmente, también de la misma tabla se combinan las componentes para calcular la predicción para un determinado horizonte de predicción <span class="math inline">\(m\)</span>, tal que:</p>
<p><span class="math display">\[
F_{t+m}=(L_t+mb_t)S_{t+m-s}
\]</span> Por tanto, las ecuaciones del algoritmos serán: <span id="eq-HW"><span class="math display">\[
\begin{eqnarray}
L_t&amp;=&amp;\alpha(\frac{Y_t}{S_{t-s}}) + (1-\alpha)[L_{t-1} + b_{t-1}]  \\
b_t&amp;=&amp;\beta(L_t - L_{t-1}) + (1-\beta)b_{t-1}  \\
S_t&amp;=&amp;\gamma\frac{Y_t}{L_t} + (1-\gamma)S_{t-s} \\
F_{t+m} &amp;=&amp; (L_t + mb_t )S_{t+m-s}
\end{eqnarray}
\tag{3.7}\]</span></span></p>
</div>
</div>
</div>
</section><section id="suavizado-exponencial-en-formato-de-espacio-de-los-estados" class="level2" data-number="3.6"><h2 data-number="3.6" class="anchored" data-anchor-id="suavizado-exponencial-en-formato-de-espacio-de-los-estados">
<span class="header-section-number">3.6</span> Suavizado exponencial en formato de espacio de los estados</h2>
<p>El uso de los diferentes métodos de suavizado exponencial (SE) analizados previamente ha sido ampliamente utilizados en la industria y academia. No obstante, un hito importante en el uso de estos método fue en el 2002 cuando un trabajo publicado por Hyndman y colaboradores (<strong>R. J. Hyndman, A. B. Koehler, R. D. Snyder, S. Grose, A state space framework for automatic forecasting using exponential smoothing methods, International Journal of Forecasting 18 (2002) 439–454</strong>) reformulaban los métodos de SE en un marco estadístico como es el del espacio de los estados. Este hito posiblemente represente el avance más importante en temas de SE dado que al disponer de un modelo estadístico se abría la puerta a los métodos de suavizado exponencial a ser tratados como procesos estocásticos y, por tanto, poder utilizar herramientas de estimación de máxima verosimilitud, selección de modelos, cálculo de intervalos de confianza teóricos y otras herramientas. Se recuerda que en las secciones anteriores los métodos de SE sólo proporcionaban las predicciones puntuales (generalmente la media) y aunque éramos capaces de estimar los intervalos de confianza, dichos intervalos se calculan de forma <strong>empírica</strong> a través de los errores de predicción, concretamente, del RMSE. En el próximo capítulo, se detallará en más profundidad los conceptos asociados a una herramienta muy útil como son los modelos expresados en espacio de los estados.</p>
<p>Los autores citados previamente, también extendieron la clasificación de Pegels para incluir otras casuísticas como el caso de tendencia amortiguada, (<strong>Hyndman, R. J., Koehler, A. B., Ord, J. K., &amp; Snyder, R. D., 2008, Forecasting with exponential smoothing: The state space approach, Springer-Verlag</strong>). La <a href="#tbl-Hyndman">Tabla&nbsp;<span>3.10</span></a> resume dicha clasificación. Esta taxonomía consiste en obtener todas las combinaciones posibles entre varias posibilidades de modelos para cada uno de los componentes: Error, tendencia y estacional (ETS, que en inglés hacen referencia a Error, Trend y Seasonal). Error: Multiplicativo (M) o aditivo (A). Tendencia o nivel: Ninguna (N), aditiva (A), aditiva amortiguada (Ad), multiplicativa (M), multiplicativa amortiguada (Md). Los autores del trabajo reconocen que el modelo con tendencia multiplicativa produce malos resultados predictivos. Estacional: Ninguna (N), aditiva (A), multiplicativa (M).</p>
<p>Otra diferencia importante con respecto a la clasificación de Pegels, es la inclusión de la componente error (<strong>E</strong>TS). Sin embargo, hay que recordar que esta componente de error sólo afecta a las predicciones de la varianza que se usarán para el cálculo de los intervalos de predicción, pero no afecta a las predicciones puntuales que coinciden con las predicciones de los métodos de SE vistos en la clasificación de Pegels.</p>
<div id="tbl-Hyndman" class="anchored">
<table class="table">
<caption>Tabla&nbsp;3.10: Clasificación de Hyndman y colaboradores. Hay una tabla para error aditivo y otra para error multiplicativo</caption>
<colgroup>
<col style="width: 19%">
<col style="width: 22%">
<col style="width: 28%">
<col style="width: 29%">
</colgroup>
<thead><tr class="header">
<th><strong>Tendencia</strong></th>
<th style="text-align: center;"></th>
<th style="text-align: center;"><strong>Estacionalidad</strong></th>
<th style="text-align: center;"></th>
</tr></thead>
<tbody>
<tr class="odd">
<td></td>
<td style="text-align: center;">(N) Ninguna</td>
<td style="text-align: center;">(A) Aditiva</td>
<td style="text-align: center;">(M) Multiplicativa</td>
</tr>
<tr class="even">
<td>(N) Ninguna</td>
<td style="text-align: center;">N,N</td>
<td style="text-align: center;">A,A</td>
<td style="text-align: center;">A,M</td>
</tr>
<tr class="odd">
<td>(A) Aditiva</td>
<td style="text-align: center;">A,N</td>
<td style="text-align: center;">A,A</td>
<td style="text-align: center;">A,M</td>
</tr>
<tr class="even">
<td>(Ad) Aditiva amortiguada</td>
<td style="text-align: center;">Ad,N</td>
<td style="text-align: center;">Ad,A</td>
<td style="text-align: center;">Ad,M</td>
</tr>
<tr class="odd">
<td>(M) Multiplicativa</td>
<td style="text-align: center;">M,N</td>
<td style="text-align: center;">M,A</td>
<td style="text-align: center;">M,M</td>
</tr>
<tr class="even">
<td>(Md) Multiplicativa amortiguada</td>
<td style="text-align: center;">Md,N</td>
<td style="text-align: center;">Md,A</td>
<td style="text-align: center;">Md,M</td>
</tr>
</tbody>
</table>
</div>


</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiado");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiado");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./07-basicsts.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Conceptos y herramientas básicas</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./03-etsSSOEenSS.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Suavizado exponencial en Espacio de los Estados</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>